/**
 * Stable country label anchors for the whole-world OnlineIntentGlobe.
 *
 * The primary anchors and localized names are derived from Natural Earth 5.1.1
 * ne_10m_admin_0_countries LABEL_X/LABEL_Y fields (public-domain map data).
 * Eleven ISO territories absent as independent Natural Earth rows use explicit interior
 * anchors. These are country-level display points only; they must never be replaced
 * with an intent, profile, device, IP, city, or venue coordinate.
 */
export type CountryCentroid = Readonly<{
  code: string;
  latitude: number;
  longitude: number;
  nameEn: string;
  nameRu: string;
  /** Испанское имя: карта подписывает страны на языке интерфейса, а он трёхъязычный. */
  nameEs: string;
}>;

export const COUNTRY_CENTROIDS: Readonly<Record<string, CountryCentroid>> = Object.freeze({
  AD: { code: "AD", latitude: 42.5476, longitude: 1.5394, nameEn: "Andorra", nameRu: "Андорра", nameEs: "Andorra" },
  AE: { code: "AE", latitude: 23.4663, longitude: 54.5473, nameEn: "United Arab Emirates", nameRu: "Объединённые Арабские Эмираты", nameEs: "Emiratos Árabes Unidos" },
  AF: { code: "AF", latitude: 34.1643, longitude: 66.4966, nameEn: "Afghanistan", nameRu: "Афганистан", nameEs: "Afganistán" },
  AG: { code: "AG", latitude: 17.3522, longitude: -61.7906, nameEn: "Antigua and Barbuda", nameRu: "Антигуа и Барбуда", nameEs: "Antigua y Barbuda" },
  AI: { code: "AI", latitude: 18.2430, longitude: -63.0264, nameEn: "Anguilla", nameRu: "Ангилья", nameEs: "Anguila" },
  AL: { code: "AL", latitude: 40.6549, longitude: 20.1138, nameEn: "Albania", nameRu: "Албания", nameEs: "Albania" },
  AM: { code: "AM", latitude: 40.4591, longitude: 44.8006, nameEn: "Armenia", nameRu: "Армения", nameEs: "Armenia" },
  AO: { code: "AO", latitude: -12.1828, longitude: 17.9842, nameEn: "Angola", nameRu: "Ангола", nameEs: "Angola" },
  AQ: { code: "AQ", latitude: -79.8432, longitude: 35.8855, nameEn: "Antarctica", nameRu: "Антарктида", nameEs: "Antártida" },
  AR: { code: "AR", latitude: -33.5012, longitude: -64.1733, nameEn: "Argentina", nameRu: "Аргентина", nameEs: "Argentina" },
  AS: { code: "AS", latitude: -14.3267, longitude: -170.7472, nameEn: "American Samoa", nameRu: "Американское Самоа", nameEs: "Samoa Americana" },
  AT: { code: "AT", latitude: 47.5189, longitude: 14.1305, nameEn: "Austria", nameRu: "Австрия", nameEs: "Austria" },
  AU: { code: "AU", latitude: -24.1295, longitude: 134.0497, nameEn: "Australia", nameRu: "Австралия", nameEs: "Australia" },
  AW: { code: "AW", latitude: 12.5174, longitude: -69.9728, nameEn: "Aruba", nameRu: "Аруба", nameEs: "Aruba" },
  AX: { code: "AX", latitude: 60.1565, longitude: 19.8697, nameEn: "Åland", nameRu: "Аландские острова", nameEs: "Aland" },
  AZ: { code: "AZ", latitude: 40.4024, longitude: 47.2110, nameEn: "Azerbaijan", nameRu: "Азербайджан", nameEs: "Azerbaiyán" },
  BA: { code: "BA", latitude: 44.0911, longitude: 18.0684, nameEn: "Bosnia and Herzegovina", nameRu: "Босния и Герцеговина", nameEs: "Bosnia y Herzegovina" },
  BB: { code: "BB", latitude: 13.1637, longitude: -59.5690, nameEn: "Barbados", nameRu: "Барбадос", nameEs: "Barbados" },
  BD: { code: "BD", latitude: 24.2150, longitude: 89.6850, nameEn: "Bangladesh", nameRu: "Бангладеш", nameEs: "Bangladesh" },
  BE: { code: "BE", latitude: 50.7854, longitude: 4.8004, nameEn: "Belgium", nameRu: "Бельгия", nameEs: "Bélgica" },
  BF: { code: "BF", latitude: 12.6730, longitude: -1.3639, nameEn: "Burkina Faso", nameRu: "Буркина-Фасо", nameEs: "Burkina Faso" },
  BG: { code: "BG", latitude: 42.5088, longitude: 25.1571, nameEn: "Bulgaria", nameRu: "Болгария", nameEs: "Bulgaria" },
  BH: { code: "BH", latitude: 26.0560, longitude: 50.5548, nameEn: "Bahrain", nameRu: "Бахрейн", nameEs: "Baréin" },
  BI: { code: "BI", latitude: -3.3328, longitude: 29.9171, nameEn: "Burundi", nameRu: "Бурунди", nameEs: "Burundi" },
  BJ: { code: "BJ", latitude: 10.3248, longitude: 2.3520, nameEn: "Benin", nameRu: "Бенин", nameEs: "Benín" },
  BL: { code: "BL", latitude: 17.9020, longitude: -62.8332, nameEn: "Saint Barthélemy", nameRu: "Сен-Бартелеми", nameEs: "San Bartolomé" },
  BM: { code: "BM", latitude: 32.2966, longitude: -64.7636, nameEn: "Bermuda", nameRu: "Бермудские Острова", nameEs: "Bermuda" },
  BN: { code: "BN", latitude: 4.4483, longitude: 114.5519, nameEn: "Brunei", nameRu: "Бруней", nameEs: "Brunéi" },
  BO: { code: "BO", latitude: -16.6660, longitude: -64.5934, nameEn: "Bolivia", nameRu: "Боливия", nameEs: "Bolivia" },
  BQ: { code: "BQ", latitude: 12.1784, longitude: -68.2385, nameEn: "Caribbean Netherlands", nameRu: "Карибские Нидерланды", nameEs: "Países Bajos Caribeños" },
  BR: { code: "BR", latitude: -12.0987, longitude: -49.5594, nameEn: "Brazil", nameRu: "Бразилия", nameEs: "Brasil" },
  BS: { code: "BS", latitude: 26.4018, longitude: -77.1467, nameEn: "The Bahamas", nameRu: "Багамские Острова", nameEs: "Bahamas" },
  BT: { code: "BT", latitude: 27.5367, longitude: 90.0403, nameEn: "Bhutan", nameRu: "Бутан", nameEs: "Bután" },
  BV: { code: "BV", latitude: -54.4208, longitude: 3.3464, nameEn: "Bouvet Island", nameRu: "Остров Буве", nameEs: "Isla Bouvet" },
  BW: { code: "BW", latitude: -22.1026, longitude: 24.1792, nameEn: "Botswana", nameRu: "Ботсвана", nameEs: "Botsuana" },
  BY: { code: "BY", latitude: 53.8219, longitude: 28.4177, nameEn: "Belarus", nameRu: "Белоруссия", nameEs: "Bielorrusia" },
  BZ: { code: "BZ", latitude: 17.2021, longitude: -88.7130, nameEn: "Belize", nameRu: "Белиз", nameEs: "Belice" },
  CA: { code: "CA", latitude: 60.3243, longitude: -101.9107, nameEn: "Canada", nameRu: "Канада", nameEs: "Canadá" },
  CC: { code: "CC", latitude: -12.1642, longitude: 96.8710, nameEn: "Cocos Islands", nameRu: "Кокосовые острова", nameEs: "Islas Cocos" },
  CD: { code: "CD", latitude: -1.8582, longitude: 23.4588, nameEn: "Democratic Republic of the Congo", nameRu: "Демократическая Республика Конго", nameEs: "República del Congo" },
  CF: { code: "CF", latitude: 6.9897, longitude: 20.9069, nameEn: "Central African Republic", nameRu: "Центральноафриканская Республика", nameEs: "República Centroafricana" },
  CG: { code: "CG", latitude: 0.1423, longitude: 15.9005, nameEn: "Republic of the Congo", nameRu: "Республика Конго", nameEs: "República del Congo" },
  CH: { code: "CH", latitude: 46.7191, longitude: 7.4640, nameEn: "Switzerland", nameRu: "Швейцария", nameEs: "Suiza" },
  CI: { code: "CI", latitude: 7.4914, longitude: -5.5686, nameEn: "Ivory Coast", nameRu: "Кот-д’Ивуар", nameEs: "Costa de Marfil" },
  CK: { code: "CK", latitude: -21.2160, longitude: -159.7857, nameEn: "Cook Islands", nameRu: "Острова Кука", nameEs: "Islas Cook" },
  CL: { code: "CL", latitude: -38.1518, longitude: -72.3189, nameEn: "Chile", nameRu: "Чили", nameEs: "Chile" },
  CM: { code: "CM", latitude: 4.5850, longitude: 12.4735, nameEn: "Cameroon", nameRu: "Камерун", nameEs: "Camerún" },
  CN: { code: "CN", latitude: 32.4982, longitude: 106.3373, nameEn: "People's Republic of China", nameRu: "Китайская Народная Республика", nameEs: "República Popular China" },
  CO: { code: "CO", latitude: 3.3731, longitude: -73.1743, nameEn: "Colombia", nameRu: "Колумбия", nameEs: "Colombia" },
  CR: { code: "CR", latitude: 10.0651, longitude: -84.0779, nameEn: "Costa Rica", nameRu: "Коста-Рика", nameEs: "Costa Rica" },
  CU: { code: "CU", latitude: 21.3340, longitude: -77.9759, nameEn: "Cuba", nameRu: "Куба", nameEs: "Cuba" },
  CV: { code: "CV", latitude: 15.0748, longitude: -23.6394, nameEn: "Cape Verde", nameRu: "Кабо-Верде", nameEs: "Cabo Verde" },
  CW: { code: "CW", latitude: 12.1450, longitude: -68.9206, nameEn: "Curaçao", nameRu: "Кюрасао", nameEs: "Curazao" },
  CX: { code: "CX", latitude: -10.4475, longitude: 105.6904, nameEn: "Christmas Island", nameRu: "Остров Рождества", nameEs: "Isla de Navidad" },
  CY: { code: "CY", latitude: 34.9133, longitude: 33.0842, nameEn: "Cyprus", nameRu: "Кипр", nameEs: "Chipre" },
  CZ: { code: "CZ", latitude: 49.8824, longitude: 15.3776, nameEn: "Czech Republic", nameRu: "Чехия", nameEs: "República Checa" },
  DE: { code: "DE", latitude: 50.9617, longitude: 9.6783, nameEn: "Germany", nameRu: "Германия", nameEs: "Alemania" },
  DJ: { code: "DJ", latitude: 11.9763, longitude: 42.4988, nameEn: "Djibouti", nameRu: "Джибути", nameEs: "Yibuti" },
  DK: { code: "DK", latitude: 55.9670, longitude: 9.0182, nameEn: "Denmark", nameRu: "Дания", nameEs: "Dinamarca" },
  DM: { code: "DM", latitude: 15.4588, longitude: -61.3450, nameEn: "Dominica", nameRu: "Доминика", nameEs: "Dominica" },
  DO: { code: "DO", latitude: 19.1041, longitude: -70.6540, nameEn: "Dominican Republic", nameRu: "Доминиканская Республика", nameEs: "República Dominicana" },
  DZ: { code: "DZ", latitude: 27.3974, longitude: 2.8082, nameEn: "Algeria", nameRu: "Алжир", nameEs: "Argelia" },
  EC: { code: "EC", latitude: -1.2591, longitude: -78.1884, nameEn: "Ecuador", nameRu: "Эквадор", nameEs: "Ecuador" },
  EE: { code: "EE", latitude: 58.7249, longitude: 25.8671, nameEn: "Estonia", nameRu: "Эстония", nameEs: "Estonia" },
  EG: { code: "EG", latitude: 26.1862, longitude: 29.4458, nameEn: "Egypt", nameRu: "Египет", nameEs: "Egipto" },
  EH: { code: "EH", latitude: 23.9676, longitude: -12.6303, nameEn: "Western Sahara", nameRu: "Западная Сахара", nameEs: "Sahara Occidental" },
  ER: { code: "ER", latitude: 15.7874, longitude: 38.2856, nameEn: "Eritrea", nameRu: "Эритрея", nameEs: "Eritrea" },
  ES: { code: "ES", latitude: 40.0910, longitude: -3.4647, nameEn: "Spain", nameRu: "Испания", nameEs: "España" },
  ET: { code: "ET", latitude: 8.0328, longitude: 39.0886, nameEn: "Ethiopia", nameRu: "Эфиопия", nameEs: "Etiopía" },
  FI: { code: "FI", latitude: 63.2524, longitude: 27.2764, nameEn: "Finland", nameRu: "Финляндия", nameEs: "Finlandia" },
  FJ: { code: "FJ", latitude: -17.8261, longitude: 177.9754, nameEn: "Fiji", nameRu: "Фиджи", nameEs: "Fiyi" },
  FK: { code: "FK", latitude: -51.6089, longitude: -58.7386, nameEn: "Falkland Islands", nameRu: "Фолклендские острова", nameEs: "Islas Malvinas" },
  FM: { code: "FM", latitude: 6.8876, longitude: 158.2340, nameEn: "Federated States of Micronesia", nameRu: "Микронезия", nameEs: "Estados Federados de Micronesia" },
  FO: { code: "FO", latitude: 62.1856, longitude: -7.0584, nameEn: "Faroe Islands", nameRu: "Фарерские острова", nameEs: "Islas Faroe" },
  FR: { code: "FR", latitude: 46.6961, longitude: 2.5523, nameEn: "France", nameRu: "Франция", nameEs: "Francia" },
  GA: { code: "GA", latitude: -0.4377, longitude: 11.8359, nameEn: "Gabon", nameRu: "Габон", nameEs: "Gabón" },
  GB: { code: "GB", latitude: 54.4027, longitude: -2.1163, nameEn: "United Kingdom", nameRu: "Великобритания", nameEs: "Reino Unido" },
  GD: { code: "GD", latitude: 12.1132, longitude: -61.6805, nameEn: "Grenada", nameRu: "Гренада", nameEs: "Granada" },
  GE: { code: "GE", latitude: 41.8701, longitude: 43.7357, nameEn: "Georgia", nameRu: "Грузия", nameEs: "Georgia" },
  GF: { code: "GF", latitude: 3.9339, longitude: -53.1258, nameEn: "French Guiana", nameRu: "Французская Гвиана", nameEs: "Guayana Francesa" },
  GG: { code: "GG", latitude: 49.4635, longitude: -2.5617, nameEn: "Guernsey", nameRu: "Гернси", nameEs: "Guernsey" },
  GH: { code: "GH", latitude: 7.7176, longitude: -1.0369, nameEn: "Ghana", nameRu: "Гана", nameEs: "Ghana" },
  GI: { code: "GI", latitude: 36.1294, longitude: -5.3467, nameEn: "Gibraltar", nameRu: "Гибралтар", nameEs: "Gibraltar" },
  GL: { code: "GL", latitude: 74.3194, longitude: -39.3353, nameEn: "Greenland", nameRu: "Гренландия", nameEs: "Groenlandia" },
  GM: { code: "GM", latitude: 13.6417, longitude: -14.9983, nameEn: "The Gambia", nameRu: "Гамбия", nameEs: "Gambia" },
  GN: { code: "GN", latitude: 10.6185, longitude: -10.0164, nameEn: "Guinea", nameRu: "Гвинея", nameEs: "Guinea" },
  GP: { code: "GP", latitude: 16.2650, longitude: -61.5510, nameEn: "Guadeloupe", nameRu: "Гваделупа", nameEs: "Guadalupe" },
  GQ: { code: "GQ", latitude: 2.3330, longitude: 8.9902, nameEn: "Equatorial Guinea", nameRu: "Экваториальная Гвинея", nameEs: "Guinea Ecuatorial" },
  GR: { code: "GR", latitude: 39.4928, longitude: 21.7257, nameEn: "Greece", nameRu: "Греция", nameEs: "Grecia" },
  GS: { code: "GS", latitude: -55.6834, longitude: -31.0632, nameEn: "South Georgia and the South Sandwich Islands", nameRu: "Южная Георгия и Южные Сандвичевы острова", nameEs: "Georgia del Sur y las islas Sandwich del Sur" },
  GT: { code: "GT", latitude: 14.9821, longitude: -90.4971, nameEn: "Guatemala", nameRu: "Гватемала", nameEs: "Guatemala" },
  GU: { code: "GU", latitude: 13.3542, longitude: 144.7036, nameEn: "Guam", nameRu: "Гуам", nameEs: "Guam" },
  GW: { code: "GW", latitude: 12.1637, longitude: -14.5241, nameEn: "Guinea-Bissau", nameRu: "Гвинея-Бисау", nameEs: "Guinea-Bisáu" },
  GY: { code: "GY", latitude: 5.1243, longitude: -58.9426, nameEn: "Guyana", nameRu: "Гайана", nameEs: "Guyana" },
  HK: { code: "HK", latitude: 22.4488, longitude: 114.0978, nameEn: "Hong Kong", nameRu: "Гонконг", nameEs: "Hong Kong" },
  HM: { code: "HM", latitude: -53.1035, longitude: 73.5052, nameEn: "Heard Island and McDonald Islands", nameRu: "Остров Херд и острова Макдональд", nameEs: "Isla Heard y las Islas McDonald" },
  HN: { code: "HN", latitude: 14.7948, longitude: -86.8876, nameEn: "Honduras", nameRu: "Гондурас", nameEs: "Honduras" },
  HR: { code: "HR", latitude: 45.8058, longitude: 16.3724, nameEn: "Croatia", nameRu: "Хорватия", nameEs: "Croacia" },
  HT: { code: "HT", latitude: 19.2638, longitude: -72.2241, nameEn: "Haiti", nameRu: "Республика Гаити", nameEs: "Haití" },
  HU: { code: "HU", latitude: 47.0868, longitude: 19.4479, nameEn: "Hungary", nameRu: "Венгрия", nameEs: "Hungría" },
  ID: { code: "ID", latitude: -0.9544, longitude: 101.8929, nameEn: "Indonesia", nameRu: "Индонезия", nameEs: "Indonesia" },
  IE: { code: "IE", latitude: 53.0787, longitude: -7.7986, nameEn: "Ireland", nameRu: "Ирландия", nameEs: "Irlanda" },
  IL: { code: "IL", latitude: 30.9111, longitude: 34.8479, nameEn: "Israel", nameRu: "Израиль", nameEs: "Israel" },
  IM: { code: "IM", latitude: 54.2208, longitude: -4.5301, nameEn: "Isle of Man", nameRu: "остров Мэн", nameEs: "Isla de Man" },
  IN: { code: "IN", latitude: 22.6869, longitude: 79.3581, nameEn: "India", nameRu: "Индия", nameEs: "India" },
  IO: { code: "IO", latitude: -6.1908, longitude: 71.3483, nameEn: "British Indian Ocean Territory", nameRu: "Британская территория в Индийском океане", nameEs: "Territorio Británico del Océano Índico" },
  IQ: { code: "IQ", latitude: 33.0940, longitude: 43.2618, nameEn: "Iraq", nameRu: "Ирак", nameEs: "Irak" },
  IR: { code: "IR", latitude: 32.1662, longitude: 54.9315, nameEn: "Iran", nameRu: "Иран", nameEs: "Irán" },
  IS: { code: "IS", latitude: 64.7793, longitude: -18.6737, nameEn: "Iceland", nameRu: "Исландия", nameEs: "Islandia" },
  IT: { code: "IT", latitude: 44.7325, longitude: 11.0769, nameEn: "Italy", nameRu: "Италия", nameEs: "Italia" },
  JE: { code: "JE", latitude: 49.2208, longitude: -2.0901, nameEn: "Jersey", nameRu: "Джерси", nameEs: "Jersey" },
  JM: { code: "JM", latitude: 18.1371, longitude: -77.3188, nameEn: "Jamaica", nameRu: "Ямайка", nameEs: "Jamaica" },
  JO: { code: "JO", latitude: 30.8050, longitude: 36.3760, nameEn: "Jordan", nameRu: "Иордания", nameEs: "Jordania" },
  JP: { code: "JP", latitude: 36.1425, longitude: 138.4422, nameEn: "Japan", nameRu: "Япония", nameEs: "Japón" },
  KE: { code: "KE", latitude: 0.5490, longitude: 37.9076, nameEn: "Kenya", nameRu: "Кения", nameEs: "Kenia" },
  KG: { code: "KG", latitude: 41.6685, longitude: 74.5326, nameEn: "Kyrgyzstan", nameRu: "Киргизия", nameEs: "Kirguistán" },
  KH: { code: "KH", latitude: 12.6476, longitude: 104.5049, nameEn: "Cambodia", nameRu: "Камбоджа", nameEs: "Camboya" },
  KI: { code: "KI", latitude: 1.8204, longitude: -157.3846, nameEn: "Kiribati", nameRu: "Кирибати", nameEs: "Kiribati" },
  KM: { code: "KM", latitude: -11.7277, longitude: 43.3181, nameEn: "Comoros", nameRu: "Коморы", nameEs: "Comoras" },
  KN: { code: "KN", latitude: 17.3366, longitude: -62.7580, nameEn: "Saint Kitts and Nevis", nameRu: "Сент-Китс и Невис", nameEs: "San Cristóbal y Nieves" },
  KP: { code: "KP", latitude: 39.8853, longitude: 126.4445, nameEn: "North Korea", nameRu: "КНДР", nameEs: "Corea del Norte" },
  KR: { code: "KR", latitude: 36.3849, longitude: 128.1295, nameEn: "South Korea", nameRu: "Республика Корея", nameEs: "Corea del Sur" },
  KW: { code: "KW", latitude: 29.4136, longitude: 47.3140, nameEn: "Kuwait", nameRu: "Кувейт", nameEs: "Kuwait" },
  KY: { code: "KY", latitude: 19.3199, longitude: -81.2405, nameEn: "Cayman Islands", nameRu: "острова Кайман", nameEs: "Islas Caimán" },
  KZ: { code: "KZ", latitude: 49.0541, longitude: 68.6855, nameEn: "Kazakhstan", nameRu: "Казахстан", nameEs: "Kazajistán" },
  LA: { code: "LA", latitude: 19.4318, longitude: 102.5339, nameEn: "Laos", nameRu: "Лаос", nameEs: "Laos" },
  LB: { code: "LB", latitude: 34.1334, longitude: 35.9929, nameEn: "Lebanon", nameRu: "Ливан", nameEs: "Líbano" },
  LC: { code: "LC", latitude: 13.8924, longitude: -60.9801, nameEn: "Saint Lucia", nameRu: "Сент-Люсия", nameEs: "Santa Lucía" },
  LI: { code: "LI", latitude: 47.1114, longitude: 9.5594, nameEn: "Liechtenstein", nameRu: "Лихтенштейн", nameEs: "Liechtenstein" },
  LK: { code: "LK", latitude: 7.5811, longitude: 80.7048, nameEn: "Sri Lanka", nameRu: "Шри-Ланка", nameEs: "Sri Lanka" },
  LR: { code: "LR", latitude: 6.4472, longitude: -9.4604, nameEn: "Liberia", nameRu: "Либерия", nameEs: "Liberia" },
  LS: { code: "LS", latitude: -29.4802, longitude: 28.2466, nameEn: "Lesotho", nameRu: "Лесото", nameEs: "Lesoto" },
  LT: { code: "LT", latitude: 55.1037, longitude: 24.0899, nameEn: "Lithuania", nameRu: "Литва", nameEs: "Lituania" },
  LU: { code: "LU", latitude: 49.7337, longitude: 6.0776, nameEn: "Luxembourg", nameRu: "Люксембург", nameEs: "Luxemburgo" },
  LV: { code: "LV", latitude: 57.0669, longitude: 25.4587, nameEn: "Latvia", nameRu: "Латвия", nameEs: "Letonia" },
  LY: { code: "LY", latitude: 26.6389, longitude: 18.0110, nameEn: "Libya", nameRu: "Ливия", nameEs: "Libia" },
  MA: { code: "MA", latitude: 31.6507, longitude: -7.1873, nameEn: "Morocco", nameRu: "Марокко", nameEs: "Marruecos" },
  MC: { code: "MC", latitude: 43.7397, longitude: 7.3983, nameEn: "Monaco", nameRu: "Монако", nameEs: "Mónaco" },
  MD: { code: "MD", latitude: 47.4350, longitude: 28.4879, nameEn: "Moldova", nameRu: "Молдавия", nameEs: "Moldavia" },
  ME: { code: "ME", latitude: 42.8031, longitude: 19.1437, nameEn: "Montenegro", nameRu: "Черногория", nameEs: "Montenegro" },
  MF: { code: "MF", latitude: 18.0813, longitude: -63.0494, nameEn: "Saint Martin", nameRu: "Сен-Мартен", nameEs: "San Martín" },
  MG: { code: "MG", latitude: -18.6283, longitude: 46.7042, nameEn: "Madagascar", nameRu: "Мадагаскар", nameEs: "Madagascar" },
  MH: { code: "MH", latitude: 7.0826, longitude: 171.1936, nameEn: "Marshall Islands", nameRu: "Маршалловы Острова", nameEs: "Islas Marshall" },
  MK: { code: "MK", latitude: 41.5582, longitude: 21.5558, nameEn: "North Macedonia", nameRu: "Северная Македония", nameEs: "Macedonia del Norte" },
  ML: { code: "ML", latitude: 18.6927, longitude: -2.0385, nameEn: "Mali", nameRu: "Мали", nameEs: "Malí" },
  MM: { code: "MM", latitude: 21.5739, longitude: 95.8045, nameEn: "Myanmar", nameRu: "Мьянма", nameEs: "Myanmar" },
  MN: { code: "MN", latitude: 45.9975, longitude: 104.1504, nameEn: "Mongolia", nameRu: "Монголия", nameEs: "Mongolia" },
  MO: { code: "MO", latitude: 22.1297, longitude: 113.5560, nameEn: "Macau", nameRu: "Макао", nameEs: "Macau" },
  MP: { code: "MP", latitude: 15.1882, longitude: 145.7344, nameEn: "Northern Mariana Islands", nameRu: "Северные Марианские острова", nameEs: "Islas Marianas del Norte" },
  MQ: { code: "MQ", latitude: 14.6415, longitude: -61.0242, nameEn: "Martinique", nameRu: "Мартиника", nameEs: "Martinica" },
  MR: { code: "MR", latitude: 19.5871, longitude: -9.7403, nameEn: "Mauritania", nameRu: "Мавритания", nameEs: "Mauritania" },
  MS: { code: "MS", latitude: 16.7372, longitude: -62.1883, nameEn: "Montserrat", nameRu: "Монтсеррат", nameEs: "Montserrat" },
  MT: { code: "MT", latitude: 35.8929, longitude: 14.4330, nameEn: "Malta", nameRu: "Мальта", nameEs: "Malta" },
  MU: { code: "MU", latitude: -20.2995, longitude: 57.5658, nameEn: "Mauritius", nameRu: "Маврикий", nameEs: "Mauricio" },
  MV: { code: "MV", latitude: 4.1744, longitude: 73.5076, nameEn: "Maldives", nameRu: "Мальдивы", nameEs: "Maldivas" },
  MW: { code: "MW", latitude: -13.3867, longitude: 33.6081, nameEn: "Malawi", nameRu: "Малави", nameEs: "Malawi" },
  MX: { code: "MX", latitude: 23.9200, longitude: -102.2894, nameEn: "Mexico", nameRu: "Мексика", nameEs: "México" },
  MY: { code: "MY", latitude: 2.5287, longitude: 113.8371, nameEn: "Malaysia", nameRu: "Малайзия", nameEs: "Malasia" },
  MZ: { code: "MZ", latitude: -13.9432, longitude: 37.8379, nameEn: "Mozambique", nameRu: "Мозамбик", nameEs: "Mozambique" },
  NA: { code: "NA", latitude: -20.5753, longitude: 17.1082, nameEn: "Namibia", nameRu: "Намибия", nameEs: "Namibia" },
  NC: { code: "NC", latitude: -21.0647, longitude: 165.0840, nameEn: "New Caledonia", nameRu: "Новая Каледония", nameEs: "Nueva Caledonia" },
  NE: { code: "NE", latitude: 17.4462, longitude: 9.5044, nameEn: "Niger", nameRu: "Нигер", nameEs: "Níger" },
  NF: { code: "NF", latitude: -29.0330, longitude: 167.9545, nameEn: "Norfolk Island", nameRu: "Норфолк", nameEs: "Isla Norfolk" },
  NG: { code: "NG", latitude: 9.4398, longitude: 7.5032, nameEn: "Nigeria", nameRu: "Нигерия", nameEs: "Nigeria" },
  NI: { code: "NI", latitude: 12.6707, longitude: -85.0693, nameEn: "Nicaragua", nameRu: "Никарагуа", nameEs: "Nicaragua" },
  NL: { code: "NL", latitude: 52.4222, longitude: 5.6114, nameEn: "Netherlands", nameRu: "Нидерланды", nameEs: "Países Bajos" },
  NO: { code: "NO", latitude: 61.3571, longitude: 9.6800, nameEn: "Norway", nameRu: "Норвегия", nameEs: "Noruega" },
  NP: { code: "NP", latitude: 28.2979, longitude: 83.6399, nameEn: "Nepal", nameRu: "Непал", nameEs: "Nepal" },
  NR: { code: "NR", latitude: -0.5203, longitude: 166.9326, nameEn: "Nauru", nameRu: "Науру", nameEs: "Nauru" },
  NU: { code: "NU", latitude: -19.0460, longitude: -169.8626, nameEn: "Niue", nameRu: "Ниуэ", nameEs: "Niue" },
  NZ: { code: "NZ", latitude: -39.7590, longitude: 172.7870, nameEn: "New Zealand", nameRu: "Новая Зеландия", nameEs: "Nueva Zelanda" },
  OM: { code: "OM", latitude: 22.1204, longitude: 57.3366, nameEn: "Oman", nameRu: "Оман", nameEs: "Omán" },
  PA: { code: "PA", latitude: 8.7220, longitude: -80.3521, nameEn: "Panama", nameRu: "Панама", nameEs: "Panamá" },
  PE: { code: "PE", latitude: -12.9767, longitude: -72.9002, nameEn: "Peru", nameRu: "Перу", nameEs: "Perú" },
  PF: { code: "PF", latitude: -17.6281, longitude: -149.4616, nameEn: "French Polynesia", nameRu: "Французская Полинезия", nameEs: "Polinesia Francesa" },
  PG: { code: "PG", latitude: -5.6953, longitude: 143.9102, nameEn: "Papua New Guinea", nameRu: "Папуа — Новая Гвинея", nameEs: "Papúa Nueva Guinea" },
  PH: { code: "PH", latitude: 11.1980, longitude: 122.4650, nameEn: "Philippines", nameRu: "Филиппины", nameEs: "Filipinas" },
  PK: { code: "PK", latitude: 29.3284, longitude: 68.5456, nameEn: "Pakistan", nameRu: "Пакистан", nameEs: "Pakistán" },
  PL: { code: "PL", latitude: 51.9903, longitude: 19.4905, nameEn: "Poland", nameRu: "Польша", nameEs: "Polonia" },
  PM: { code: "PM", latitude: 47.0403, longitude: -56.3324, nameEn: "Saint Pierre and Miquelon", nameRu: "Сен-Пьер и Микелон", nameEs: "San Pedro y Miquelón" },
  PN: { code: "PN", latitude: -24.3646, longitude: -128.3175, nameEn: "Pitcairn Islands", nameRu: "Острова Питкэрн", nameEs: "Islas Pitcairn" },
  PR: { code: "PR", latitude: 18.2347, longitude: -66.4811, nameEn: "Puerto Rico", nameRu: "Пуэрто-Рико", nameEs: "Puerto Rico" },
  PS: { code: "PS", latitude: 32.0474, longitude: 35.2913, nameEn: "Palestine", nameRu: "Палестина", nameEs: "Palestina" },
  PT: { code: "PT", latitude: 39.6067, longitude: -8.2718, nameEn: "Portugal", nameRu: "Португалия", nameEs: "Portugal" },
  PW: { code: "PW", latitude: 7.5183, longitude: 134.5802, nameEn: "Palau", nameRu: "Палау", nameEs: "Palaos" },
  PY: { code: "PY", latitude: -21.6745, longitude: -60.1464, nameEn: "Paraguay", nameRu: "Парагвай", nameEs: "Paraguay" },
  QA: { code: "QA", latitude: 25.2374, longitude: 51.1435, nameEn: "Qatar", nameRu: "Катар", nameEs: "Catar" },
  RE: { code: "RE", latitude: -21.1151, longitude: 55.5364, nameEn: "Réunion", nameRu: "Реюньон", nameEs: "Reunión" },
  RO: { code: "RO", latitude: 45.7332, longitude: 24.9726, nameEn: "Romania", nameRu: "Румыния", nameEs: "Rumania" },
  RS: { code: "RS", latitude: 44.1899, longitude: 20.7880, nameEn: "Serbia", nameRu: "Сербия", nameEs: "Serbia" },
  RU: { code: "RU", latitude: 58.2494, longitude: 44.6865, nameEn: "Russia", nameRu: "Россия", nameEs: "Rusia" },
  RW: { code: "RW", latitude: -1.8972, longitude: 30.1039, nameEn: "Rwanda", nameRu: "Руанда", nameEs: "Ruanda" },
  SA: { code: "SA", latitude: 23.8069, longitude: 44.6996, nameEn: "Saudi Arabia", nameRu: "Саудовская Аравия", nameEs: "Arabia Saudí" },
  SB: { code: "SB", latitude: -8.0295, longitude: 159.1705, nameEn: "Solomon Islands", nameRu: "Соломоновы Острова", nameEs: "Islas Salomón" },
  SC: { code: "SC", latitude: -4.6767, longitude: 55.4802, nameEn: "Seychelles", nameRu: "Сейшельские Острова", nameEs: "Seychelles" },
  SD: { code: "SD", latitude: 16.3307, longitude: 29.2607, nameEn: "Sudan", nameRu: "Судан", nameEs: "Sudán" },
  SE: { code: "SE", latitude: 65.8592, longitude: 19.0171, nameEn: "Sweden", nameRu: "Швеция", nameEs: "Suecia" },
  SG: { code: "SG", latitude: 1.3666, longitude: 103.8169, nameEn: "Singapore", nameRu: "Сингапур", nameEs: "Singapur" },
  SH: { code: "SH", latitude: -15.9505, longitude: -5.7126, nameEn: "Saint Helena", nameRu: "Остров Святой Елены", nameEs: "Santa Elena" },
  SI: { code: "SI", latitude: 46.0608, longitude: 14.9153, nameEn: "Slovenia", nameRu: "Словения", nameEs: "Eslovenia" },
  SJ: { code: "SJ", latitude: 78.2232, longitude: 15.6469, nameEn: "Svalbard and Jan Mayen", nameRu: "Шпицберген и Ян-Майен", nameEs: "Svalbard y Jan Mayen" },
  SK: { code: "SK", latitude: 48.7340, longitude: 19.0499, nameEn: "Slovakia", nameRu: "Словакия", nameEs: "Eslovaquia" },
  SL: { code: "SL", latitude: 8.6174, longitude: -11.7637, nameEn: "Sierra Leone", nameRu: "Сьерра-Леоне", nameEs: "Sierra Leone" },
  SM: { code: "SM", latitude: 43.9339, longitude: 12.4412, nameEn: "San Marino", nameRu: "Сан-Марино", nameEs: "San Marino" },
  SN: { code: "SN", latitude: 15.1381, longitude: -14.7786, nameEn: "Senegal", nameRu: "Сенегал", nameEs: "Senegal" },
  SO: { code: "SO", latitude: 3.5689, longitude: 45.1924, nameEn: "Somalia", nameRu: "Сомали", nameEs: "Somalia" },
  SR: { code: "SR", latitude: 4.1440, longitude: -55.9109, nameEn: "Suriname", nameRu: "Суринам", nameEs: "Surinam" },
  SS: { code: "SS", latitude: 7.2305, longitude: 30.3902, nameEn: "South Sudan", nameRu: "Южный Судан", nameEs: "Sudán del Sur" },
  ST: { code: "ST", latitude: 0.9709, longitude: 7.0210, nameEn: "São Tomé and Príncipe", nameRu: "Сан-Томе и Принсипи", nameEs: "Santo Tomé y Príncipe" },
  SV: { code: "SV", latitude: 13.6854, longitude: -88.8901, nameEn: "El Salvador", nameRu: "Сальвадор", nameEs: "El Salvador" },
  SX: { code: "SX", latitude: 18.0409, longitude: -63.0701, nameEn: "Sint Maarten", nameRu: "Синт-Мартен", nameEs: "San Martín" },
  SY: { code: "SY", latitude: 35.0066, longitude: 38.2778, nameEn: "Syria", nameRu: "Сирия", nameEs: "Siria" },
  SZ: { code: "SZ", latitude: -26.5337, longitude: 31.4673, nameEn: "Eswatini", nameRu: "Эсватини", nameEs: "Eswatini" },
  TC: { code: "TC", latitude: 21.8166, longitude: -71.7527, nameEn: "Turks and Caicos Islands", nameRu: "Тёркс и Кайкос", nameEs: "Islas Turcas y Caicos" },
  TD: { code: "TD", latitude: 15.1430, longitude: 18.6450, nameEn: "Chad", nameRu: "Чад", nameEs: "Chad" },
  TF: { code: "TF", latitude: -49.3037, longitude: 69.1221, nameEn: "French Southern and Antarctic Lands", nameRu: "Французские Южные и Антарктические территории", nameEs: "Territorios Franceses del Sur y Antártida" },
  TG: { code: "TG", latitude: 8.8072, longitude: 1.0581, nameEn: "Togo", nameRu: "Того", nameEs: "Togo" },
  TH: { code: "TH", latitude: 15.4597, longitude: 101.0732, nameEn: "Thailand", nameRu: "Таиланд", nameEs: "Tailandia" },
  TJ: { code: "TJ", latitude: 38.1998, longitude: 72.5873, nameEn: "Tajikistan", nameRu: "Таджикистан", nameEs: "Tayikistán" },
  TK: { code: "TK", latitude: -9.2002, longitude: -171.8484, nameEn: "Tokelau", nameRu: "Токелау", nameEs: "Tokelau" },
  TL: { code: "TL", latitude: -8.8037, longitude: 125.8547, nameEn: "East Timor", nameRu: "Восточный Тимор", nameEs: "Timor Oriental" },
  TM: { code: "TM", latitude: 39.8552, longitude: 58.6766, nameEn: "Turkmenistan", nameRu: "Туркмения", nameEs: "Turkmenistán" },
  TN: { code: "TN", latitude: 33.6873, longitude: 9.0079, nameEn: "Tunisia", nameRu: "Тунис", nameEs: "Túnez" },
  TO: { code: "TO", latitude: -21.2100, longitude: -175.1630, nameEn: "Tonga", nameRu: "Тонга", nameEs: "Tonga" },
  TR: { code: "TR", latitude: 39.3454, longitude: 34.5083, nameEn: "Turkey", nameRu: "Турция", nameEs: "Turquía" },
  TT: { code: "TT", latitude: 10.9989, longitude: -60.9184, nameEn: "Trinidad and Tobago", nameRu: "Тринидад и Тобаго", nameEs: "Trinidad y Tobago" },
  TV: { code: "TV", latitude: -8.5137, longitude: 179.2096, nameEn: "Tuvalu", nameRu: "Тувалу", nameEs: "Tuvalu" },
  TW: { code: "TW", latitude: 23.6524, longitude: 120.8682, nameEn: "Taiwan", nameRu: "Тайвань", nameEs: "Taiwán" },
  TZ: { code: "TZ", latitude: -6.0519, longitude: 34.9592, nameEn: "Tanzania", nameRu: "Танзания", nameEs: "Tanzania" },
  UA: { code: "UA", latitude: 49.7247, longitude: 32.1409, nameEn: "Ukraine", nameRu: "Украина", nameEs: "Ucrania" },
  UG: { code: "UG", latitude: 1.9726, longitude: 32.9486, nameEn: "Uganda", nameRu: "Уганда", nameEs: "Uganda" },
  UM: { code: "UM", latitude: 19.2857, longitude: 166.6445, nameEn: "United States Minor Outlying Islands", nameRu: "Внешние малые острова США", nameEs: "Islas Ultramarinas Menores de Estados Unidos" },
  US: { code: "US", latitude: 39.5385, longitude: -97.4826, nameEn: "United States of America", nameRu: "США", nameEs: "Estados Unidos de América" },
  UY: { code: "UY", latitude: -32.9611, longitude: -55.9669, nameEn: "Uruguay", nameRu: "Уругвай", nameEs: "Uruguay" },
  UZ: { code: "UZ", latitude: 41.6936, longitude: 64.0054, nameEn: "Uzbekistan", nameRu: "Узбекистан", nameEs: "Uzbekistán" },
  VA: { code: "VA", latitude: 41.9033, longitude: 12.4534, nameEn: "Vatican City", nameRu: "Ватикан", nameEs: "Ciudad del Vaticano" },
  VC: { code: "VC", latitude: 13.0879, longitude: -61.3359, nameEn: "Saint Vincent and the Grenadines", nameRu: "Сент-Винсент и Гренадины", nameEs: "San Vicente y las Granadinas" },
  VE: { code: "VE", latitude: 7.1825, longitude: -64.5994, nameEn: "Venezuela", nameRu: "Венесуэла", nameEs: "Venezuela" },
  VG: { code: "VG", latitude: 18.4266, longitude: -64.6366, nameEn: "British Virgin Islands", nameRu: "Британские Виргинские острова", nameEs: "Islas Vírgenes Británicas" },
  VI: { code: "VI", latitude: 17.7467, longitude: -64.7792, nameEn: "United States Virgin Islands", nameRu: "Американские Виргинские острова", nameEs: "Islas Vírgenes de los Estados Unidos" },
  VN: { code: "VN", latitude: 21.7154, longitude: 105.3873, nameEn: "Vietnam", nameRu: "Вьетнам", nameEs: "Vietnam" },
  VU: { code: "VU", latitude: -15.3715, longitude: 166.9088, nameEn: "Vanuatu", nameRu: "Вануату", nameEs: "Vanuatu" },
  WF: { code: "WF", latitude: -14.2864, longitude: -178.1374, nameEn: "Wallis and Futuna", nameRu: "Уоллис и Футуна", nameEs: "Wallis y Futuna" },
  WS: { code: "WS", latitude: -13.6391, longitude: -172.4382, nameEn: "Samoa", nameRu: "Самоа", nameEs: "Samoa" },
  XK: { code: "XK", latitude: 42.5936, longitude: 20.8607, nameEn: "Kosovo", nameRu: "Республика Косово", nameEs: "Kosovo" },
  YE: { code: "YE", latitude: 15.3282, longitude: 45.8744, nameEn: "Yemen", nameRu: "Йемен", nameEs: "Yemen" },
  YT: { code: "YT", latitude: -12.8275, longitude: 45.1662, nameEn: "Mayotte", nameRu: "Майотта", nameEs: "Mayotte" },
  ZA: { code: "ZA", latitude: -29.7088, longitude: 23.6657, nameEn: "South Africa", nameRu: "ЮАР", nameEs: "Sudáfrica" },
  ZM: { code: "ZM", latitude: -14.6608, longitude: 26.3953, nameEn: "Zambia", nameRu: "Замбия", nameEs: "Zambia" },
  ZW: { code: "ZW", latitude: -18.9116, longitude: 29.9254, nameEn: "Zimbabwe", nameRu: "Зимбабве", nameEs: "Zimbabue" },
});

export function countryCentroid(code: string): CountryCentroid | undefined {
  return COUNTRY_CENTROIDS[String(code || '').trim().toUpperCase()];
}
