/**
 * СГЕНЕРИРОВАННЫЙ ФАЙЛ. Не править руками.
 *
 * Источник: kleal-ms/shared/interests.json
 * Обновить: python3 kleal-ms/tools/gen_interests_tree.py --apply
 *
 * Дерево интересов для карты. Раньше оно было отдельным литералом и знало 320 ключей из 447 —
 * остальные не имели подписи и на карту не попадали. Теперь источник общий с сервером: добавить
 * интерес значит дописать строку в реестр, а не в двух местах, которые потом расходятся.
 *
 * Синонимы на экран не идут: football и soccer — один пузырь, второй по-прежнему понимается поиском.
 */
export type TreeNode = { key: string; ru: string; en: string; icon?: string; kids?: TreeNode[] };

const N = (key: string, ru: string, en: string, kids?: TreeNode[]): TreeNode => ({ key, ru, en, kids });
const TOP = (key: string, ru: string, en: string, icon: string, kids: TreeNode[]): TreeNode =>
  ({ key, ru, en, icon, kids });

export const TREE: TreeNode[] = [
  TOP('sports', 'Спорт', 'Sport', 'sports', [
    N('team', 'Командный', 'Team', [
      N('football', 'Футбол', 'Football'),
      N('basketball', 'Баскетбол', 'Basketball'),
      N('volleyball', 'Волейбол', 'Volleyball'),
      N('handball', 'Гандбол', 'Handball'),
      N('rugby', 'Регби', 'Rugby'),
      N('cricket', 'Крикет', 'cricket'),
      N('hockey', 'Хоккей', 'Hockey'),
      N('baseball', 'Бейсбол', 'baseball'),
      N('futsal', 'Мини-футбол', 'Futsal'),
      N('ultimate', 'Фрисби', 'ultimate'),
      N('waterpolo', 'Водное поло', 'waterpolo'),
    ]),
    N('racket', 'Ракетки', 'Racquets', [
      N('tennis', 'Теннис', 'Tennis'),
      N('padel', 'Падел', 'Padel'),
      N('badminton', 'Бадминтон', 'Badminton'),
      N('squash', 'Сквош', 'Squash'),
      N('pingpong', 'Настольный теннис', 'Ping-pong'),
      N('tabletennis', 'Настольный теннис', 'tabletennis'),
      N('pickleball', 'Пиклбол', 'Pickleball'),
      N('racquetball', 'Ракетбол', 'racquetball'),
    ]),
    N('endurance', 'Выносливость', 'Endurance', [
      N('running', 'Бег', 'Running'),
      N('cycling', 'Вело', 'Cycling'),
      N('swimming', 'Плавание', 'Swimming'),
      N('triathlon', 'Триатлон', 'Triathlon'),
      N('marathon', 'Марафон', 'Marathon'),
      N('rowing', 'Гребля', 'Rowing'),
      N('spinning', 'Велотренажер', 'spinning'),
      N('hyrox', 'Hyrox', 'hyrox'),
      N('duathlon', 'Дуатлон', 'duathlon'),
    ]),
    N('strength', 'Зал и сила', 'Gym & strength', [
      N('gym', 'Зал', 'Gym'),
      N('fitness', 'Фитнес', 'fitness'),
      N('crossfit', 'Кроссфит', 'CrossFit'),
      N('boxing', 'Бокс', 'Boxing'),
      N('mma', 'ММА', 'MMA'),
      N('climbing', 'Скалолазание', 'Climbing'),
      N('bouldering', 'Боулдеринг', 'Bouldering'),
      N('calisthenics', 'Турники', 'Calisthenics'),
      N('powerlifting', 'Пауэрлифтинг', 'Powerlifting'),
      N('weightlifting', 'Тяжелая атлетика', 'weightlifting'),
      N('kettlebell', 'Гири', 'kettlebell'),
      N('kickboxing', 'Кикбоксинг', 'kickboxing'),
      N('judo', 'Дзюдо', 'judo'),
      N('karate', 'Карате', 'karate'),
      N('bjj', 'Джиу-джитсу', 'BJJ'),
      N('wrestling', 'Борьба', 'wrestling'),
      N('muaythai', 'Муай тай', 'muaythai'),
      N('fencing', 'Фехтование', 'fencing'),
    ]),
    N('mindbody', 'Тело и практики', 'Body & practice', [
      N('yoga', 'Йога', 'Yoga'),
      N('pilates', 'Пилатес', 'Pilates'),
      N('stretching', 'Растяжка', 'Stretching'),
      N('meditation', 'Медитация', 'Meditation'),
      N('breathwork', 'Дыхание', 'Breathwork'),
      N('taichi', 'Тайцзи', 'Tai chi'),
      N('qigong', 'Цигун', 'qigong'),
    ]),
  ]),
  TOP('social', 'Общение', 'Social', 'social', [
    N('coffee', 'Кофе', 'Coffee', [
      N('tea', 'Чай', 'Tea'),
      N('brunch', 'Бранчи', 'Brunch'),
      N('cafe', 'По кофейням', 'Cafe hopping'),
      N('matcha', 'Матча', 'Matcha'),
      N('espresso', 'Эспрессо', 'Espresso'),
    ]),
    N('dining', 'Поесть', 'Eating out', [
      N('dinner', 'Ужины', 'Dinners'),
      N('lunch', 'Обед', 'lunch'),
      N('food', 'Еда', 'food'),
      N('restaurant', 'Рестораны', 'Restaurants'),
      N('cooking', 'Готовка', 'Cooking'),
    ]),
    N('nightlife', 'Ночная жизнь', 'Nightlife', [
      N('bar', 'Бары', 'Bars'),
      N('drinks', 'Напитки', 'drinks'),
      N('pub', 'Паб', 'pub'),
      N('beer', 'Пиво', 'Beer'),
      N('wine', 'Вино', 'Wine'),
      N('party', 'Вечеринки', 'Parties'),
      N('club', 'Клубы', 'Clubs'),
      N('clubbing', 'Клуб', 'clubbing'),
      N('cocktails', 'Коктейли', 'Cocktails'),
      N('mezcal', 'Мескаль', 'mezcal'),
      N('sake', 'Саке', 'sake'),
    ]),
    N('casual', 'Просто погулять', 'Just hang out', [
      N('walk', 'Прогулки', 'Walks'),
      N('walking', 'Ходьба', 'walking'),
      N('stroll', 'Прогулка', 'stroll'),
      N('hang', 'Встреча', 'hang'),
      N('hangout', 'Поболтать', 'Hang out'),
      N('chill', 'Релакс', 'chill'),
      N('talk', 'Разговор', 'talk'),
      N('chat', 'Болтовня', 'chat'),
      N('park', 'Парки', 'Parks'),
      N('terrace', 'Террасы', 'Terraces'),
    ]),
    N('foodie', 'Гурман', 'foodie', [
      N('baking', 'Выпечка', 'Baking'),
      N('bbq', 'Барбекю', 'bbq'),
      N('streetfood', 'Стритфуд', 'Street food'),
      N('vegan', 'Веган', 'Vegan'),
      N('vegetarian', 'Вегетарианство', 'vegetarian'),
      N('tapas', 'Тапас', 'Tapas'),
      N('sushi', 'Суши', 'Sushi'),
      N('picnic', 'Пикники', 'Picnics'),
      N('ramen', 'Рамен', 'Ramen'),
      N('pizza', 'Пицца', 'pizza'),
      N('pasta', 'Паста', 'pasta'),
    ]),
    N('wellness', 'Спа и забота', 'Spa & self-care', [
      N('spa', 'Спа', 'Spa'),
      N('sauna', 'Сауна', 'Sauna'),
      N('selfcare', 'Забота о себе', 'Self-care'),
      N('massage', 'Массаж', 'Massage'),
    ]),
    N('community', 'Волонтёрство', 'Volunteering', [
      N('volunteering', 'Помогать', 'Volunteering'),
      N('charity', 'Благотворительность', 'Charity'),
      N('meetup', 'Митапы', 'Meetups'),
      N('activism', 'Активизм', 'Activism'),
      N('sustainability', 'Экология', 'Sustainability'),
    ]),
    N('pets', 'Питомцы', 'Pets', [
      N('dogs', 'Собаки', 'Dogs'),
      N('dog', 'Собака', 'dog'),
      N('cats', 'Кошки', 'Cats'),
      N('dogwalk', 'Выгул вместе', 'Dog walks'),
    ]),
    N('family', 'Семья и дети', 'Family & kids', [
      N('parenting', 'Родительство', 'Parenting'),
      N('kids', 'С детьми', 'With kids'),
      N('playdate', 'Плейдейты', 'Playdates'),
      N('mums', 'Мамы', 'mums'),
    ]),
  ]),
  TOP('games', 'Игры', 'Games', 'games', [
    N('esports', 'Киберспорт', 'Esports', [
      N('dota', 'Dota', 'Dota'),
      N('valorant', 'Valorant', 'Valorant'),
      N('cs', 'CS', 'CS'),
      N('league', 'League of Legends', 'League of Legends'),
      N('apex', 'Apex', 'Apex'),
      N('fortnite', 'Фортнайт', 'fortnite'),
      N('fifa', 'FIFA', 'FIFA'),
      N('overwatch', 'Overwatch', 'Overwatch'),
      N('gaming', 'Игры', 'gaming'),
      N('rocketleague', 'Rocket League', 'Rocket League'),
      N('r6', 'Rainbow Six', 'r6'),
      N('rainbow6', 'Рейнбоу', 'rainbow6'),
      N('starcraft', 'Старкрафт', 'starcraft'),
      N('hearthstone', 'Коллекционная карта', 'hearthstone'),
      N('tekken', 'Tekken', 'tekken'),
      N('smash', 'Smash Bros', 'smash'),
      N('cod', 'Шутер', 'cod'),
      N('warzone', 'Батл-рояль', 'warzone'),
    ]),
    N('tabletop', 'Настолки', 'Board games', [
      N('chess', 'Шахматы', 'Chess'),
      N('boardgames', 'Настольные', 'Board games'),
      N('poker', 'Покер', 'Poker'),
      N('cards', 'Карты', 'cards'),
      N('dnd', 'Ролевые', 'Tabletop RPG'),
      N('catan', 'Катан', 'Catan'),
      N('monopoly', 'Монополия', 'monopoly'),
      N('risk', 'Риск', 'risk'),
      N('magic', 'Magic', 'Magic'),
      N('mtg', 'Мэджик', 'mtg'),
      N('warhammer', 'Warhammer', 'Warhammer'),
      N('ttrpg', 'Ролевая игра', 'ttrpg'),
      N('trivia', 'Квизы', 'Trivia'),
      N('quiz', 'Викторина', 'quiz'),
      N('mahjong', 'Маджонг', 'mahjong'),
      N('backgammon', 'Нарды', 'Backgammon'),
      N('escaperoom', 'Квесты', 'Escape rooms'),
    ]),
    N('console', 'Консоли', 'Console', [
      N('playstation', 'PlayStation', 'PlayStation'),
      N('xbox', 'Xbox', 'Xbox'),
      N('nintendo', 'Nintendo', 'Nintendo'),
      N('switch', 'Нинтендо', 'switch'),
    ]),
    N('pc', 'PC', 'PC', [
      N('minecraft', 'Minecraft', 'Minecraft'),
      N('roblox', 'Роблокс', 'roblox'),
      N('valheim', 'Valheim', 'Valheim'),
      N('terraria', 'Terraria', 'Terraria'),
      N('stardew', 'Stardew Valley', 'Stardew Valley'),
    ]),
    N('mobile', 'Мобильные игры', 'mobile', [
      N('clashroyale', 'Clash Royale', 'Clash Royale'),
      N('pubg', 'PUBG', 'PUBG'),
      N('genshin', 'Genshin', 'Genshin'),
      N('mobilegaming', 'Мобильные', 'Mobile'),
    ]),
  ]),
  TOP('culture', 'Культура', 'Culture', 'culture', [
    N('screen', 'Кино и сериалы', 'Films & series', [
      N('cinema', 'Кино', 'Films'),
      N('series', 'Сериалы', 'Series'),
      N('documentary', 'Документальное', 'Documentary'),
      N('netflix', 'Нетфликс', 'netflix'),
      N('marvel', 'Marvel', 'Marvel'),
      N('sitcom', 'Ситкомы', 'Sitcoms'),
    ]),
    N('visual', 'Искусство', 'Art', [
      N('art', 'Искусство', 'art'),
      N('museum', 'Музеи', 'Museums'),
      N('gallery', 'Галереи', 'Galleries'),
      N('photography', 'Фотография', 'Photography'),
      N('exhibition', 'Выставки', 'Exhibitions'),
      N('painting', 'Живопись', 'Painting'),
      N('sketching', 'Скетчинг', 'Sketching'),
      N('illustration', 'Иллюстрация', 'illustration'),
      N('streetart', 'Стритарт', 'Street art'),
      N('graffiti', 'Граффити', 'graffiti'),
      N('sculpture', 'Скульптура', 'sculpture'),
    ]),
    N('stage', 'Сцена', 'Stage', [
      N('theatre', 'Театр', 'Theatre'),
      N('opera', 'Опера', 'Opera'),
      N('ballet', 'Балет', 'Ballet'),
      N('standup', 'Стендап', 'Stand-up'),
      N('comedy', 'Комедия', 'comedy'),
      N('improv', 'Импров', 'Improv'),
      N('musical', 'Мюзиклы', 'Musicals'),
      N('circus', 'Цирк', 'circus'),
    ]),
    N('reading', 'Книги', 'Books', [
      N('books', 'Читать', 'Reading'),
      N('literature', 'Классика', 'Literature'),
      N('bookclub', 'Книжный клуб', 'Book club'),
      N('scifi', 'Фантастика', 'Sci-fi'),
      N('fantasy', 'Фэнтези', 'Fantasy'),
      N('nonfiction', 'Нон-фикшн', 'Non-fiction'),
    ]),
    N('urbanism', 'Урбанистика', 'Urbanism', [
      N('architecture', 'Архитектура', 'Architecture'),
      N('city', 'Город', 'city'),
    ]),
    N('anime', 'Аниме и Азия', 'Anime & Asia', [
      N('manga', 'Манга', 'Manga'),
      N('kdrama', 'К-дорамы', 'K-drama'),
      N('cosplay', 'Косплей', 'Cosplay'),
      N('kpop', 'K-pop', 'K-pop'),
      N('cartoons', 'Мультфильмы', 'Cartoons'),
    ]),
    N('craft', 'Рукоделие', 'Craft', [
      N('pottery', 'Керамика', 'Pottery'),
      N('ceramics', 'Керамика', 'ceramics'),
      N('knitting', 'Вязание', 'Knitting'),
      N('crochet', 'Вязание крючком', 'crochet'),
      N('sewing', 'Шитьё', 'Sewing'),
      N('woodworking', 'Дерево', 'Woodworking'),
      N('calligraphy', 'Каллиграфия', 'Calligraphy'),
      N('diy', 'Своими руками', 'DIY'),
    ]),
    N('writing', 'Тексты', 'Writing', [
      N('poetry', 'Поэзия', 'Poetry'),
      N('journaling', 'Дневник', 'Journaling'),
      N('blogging', 'Блог', 'Blogging'),
    ]),
    N('history', 'История и город', 'History & city', [
      N('heritage', 'Наследие', 'Heritage'),
      N('archaeology', 'Археология', 'Archaeology'),
    ]),
  ]),
  TOP('tech', 'Дело', 'Work & tech', 'tech', [
    N('startups', 'Стартапы', 'Startups', [
      N('startup', 'Свой проект', 'Own project'),
      N('product', 'Продукт', 'Product'),
      N('founder', 'Основателям', 'Founders'),
      N('entrepreneur', 'Предпринимательство', 'Entrepreneurship'),
      N('business', 'Бизнес', 'Business'),
    ]),
    N('engineering', 'Код и ИИ', 'Code & AI', [
      N('ai', 'ИИ', 'AI'),
      N('programming', 'Программирование', 'programming'),
      N('coding', 'Программирование', 'Coding'),
      N('software', 'Программное обеспечение', 'software'),
      N('data', 'Данные', 'Data'),
      N('crypto', 'Криптовалюты', 'Crypto'),
      N('blockchain', 'Блокчейн', 'blockchain'),
      N('devops', 'DevOps', 'DevOps'),
      N('cloud', 'Облако', 'cloud'),
      N('cybersecurity', 'Безопасность', 'Security'),
      N('security', 'Безопасность', 'security'),
      N('python', 'Python', 'Python'),
      N('javascript', 'JavaScript', 'JavaScript'),
      N('rust', 'Rust', 'Rust'),
      N('golang', 'Go', 'golang'),
      N('opensource', 'Опенсорс', 'Open source'),
      N('frontend', 'Фронтенд', 'frontend'),
      N('backend', 'Бэкенд', 'backend'),
    ]),
    N('career', 'Карьера и связи', 'Career & network', [
      N('networking', 'Нетворкинг', 'Networking'),
      N('investing', 'Инвестиции', 'Investing'),
      N('investor', 'Инвестор', 'investor'),
      N('mentorship', 'Менторство', 'Mentorship'),
      N('consulting', 'Консалтинг', 'consulting'),
      N('finance', 'Финансы', 'Finance'),
      N('vc', 'Венчурный капитал', 'vc'),
      N('freelance', 'Фриланс', 'Freelance'),
      N('remote', 'Удалёнка', 'Remote'),
      N('coworking', 'Коворкинг', 'Coworking'),
    ]),
    N('design', 'Дизайн', 'Design', [
      N('ux', 'UX', 'UX'),
      N('ui', 'UI', 'UI'),
      N('figma', 'Figma', 'Figma'),
      N('branding', 'Бренд', 'Branding'),
      N('typography', 'Типографика', 'Typography'),
      N('motion', 'Моушн', 'Motion'),
    ]),
    N('dataai', 'Данные и ИИ', 'dataai', [
      N('datascience', 'Data Science', 'datascience'),
      N('analytics', 'Аналитика', 'analytics'),
      N('statistics', 'Статистика', 'statistics'),
      N('bigdata', 'Большие данные', 'bigdata'),
    ]),
    N('web3', 'Крипта', 'Crypto', [
      N('defi', 'DeFi', 'DeFi'),
      N('nft', 'NFT', 'NFT'),
      N('dao', 'DAO', 'DAO'),
      N('ethereum', 'Эфир', 'Ethereum'),
      N('bitcoin', 'Биткоин', 'Bitcoin'),
      N('solidity', 'Solidity', 'solidity'),
      N('degen', 'Degen', 'degen'),
    ]),
    N('growth', 'Маркетинг', 'Marketing', [
      N('marketing', 'Маркетинг', 'Marketing'),
      N('sales', 'Продажи', 'Sales'),
      N('saas', 'SaaS', 'SaaS'),
      N('b2b', 'B2B', 'b2b'),
      N('pm', 'Продакт-менеджмент', 'Product management'),
    ]),
  ]),
  TOP('music', 'Музыка', 'Music', 'music', [
    N('listening', 'Концерты', 'Live music', [
      N('concert', 'Концерты', 'Concerts'),
      N('gig', 'Небольшие площадки', 'Small gigs'),
      N('festival', 'Фестивали', 'Festivals'),
      N('music', 'Музыка', 'Music'),
      N('vinyl', 'Винил', 'Vinyl'),
      N('livemusic', 'Живая музыка', 'Live music'),
      N('playlist', 'Плейлист', 'playlist'),
    ]),
    N('making', 'Играю сам', 'I play', [
      N('guitar', 'Гитара', 'Guitar'),
      N('piano', 'Пианино', 'Piano'),
      N('drums', 'Барабаны', 'Drums'),
      N('dj', 'Диджеинг', 'DJing'),
      N('jam', 'Джем', 'jam'),
      N('producing', 'Продакшн', 'Producing'),
      N('singing', 'Вокал', 'Singing'),
      N('karaoke', 'Караоке', 'Karaoke'),
      N('band', 'Группа', 'Band'),
      N('bass', 'Бас', 'Bass'),
      N('synth', 'Синтезатор', 'synth'),
      N('ableton', 'Ableton', 'ableton'),
      N('songwriting', 'Песни', 'songwriting'),
      N('choir', 'Хор', 'choir'),
    ]),
    N('electronic', 'Электроника', 'Electronic', [
      N('rave', 'Рейвы', 'Raves'),
      N('techno', 'Техно', 'Techno'),
      N('edm', 'EDM', 'EDM'),
    ]),
    N('genres', 'Жанры', 'Genres', [
      N('jazz', 'Джаз', 'Jazz'),
      N('rock', 'Рок', 'Rock'),
      N('hiphop', 'Хип-хоп', 'Hip-hop'),
      N('rap', 'Рэп', 'rap'),
      N('classical', 'Классика', 'Classical'),
      N('indie', 'Инди', 'Indie'),
      N('pop', 'Поп', 'pop'),
      N('metal', 'Метал', 'Metal'),
      N('punk', 'Панк', 'punk'),
      N('reggae', 'Регги', 'reggae'),
      N('funk', 'Фанк', 'Funk'),
      N('soul', 'Соул', 'Soul'),
      N('house', 'Хаус', 'House'),
      N('disco', 'Диско', 'disco'),
    ]),
    N('dance', 'Танцы', 'Dance', [
      N('salsa', 'Сальса', 'Salsa'),
      N('bachata', 'Бачата', 'Bachata'),
      N('tango', 'Танго', 'Tango'),
      N('swing', 'Свинг', 'Swing'),
      N('ballroom', 'Бальные', 'Ballroom'),
      N('zumba', 'Зумба', 'Zumba'),
    ]),
  ]),
  TOP('outdoors', 'Природа', 'Outdoors', 'outdoors', [
    N('hiking', 'Походы', 'Hiking', [
      N('trekking', 'Треккинг', 'Trekking'),
      N('nature', 'Природа', 'nature'),
      N('camping', 'Кемпинг', 'Camping'),
      N('mountains', 'Горы', 'Mountains'),
      N('trail', 'Тропы', 'Trails'),
      N('outdoor', 'На открытом воздухе', 'outdoor'),
      N('outdoors', 'Природа', 'Outdoors'),
      N('backpacking', 'С рюкзаком', 'Backpacking'),
      N('trailrunning', 'Трейлраннинг', 'Trail running'),
      N('mountaineering', 'Альпинизм', 'mountaineering'),
    ]),
    N('watersnow', 'Вода и снег', 'Water & snow', [
      N('surfing', 'Сёрфинг', 'Surfing'),
      N('kayaking', 'Каяк', 'Kayaking'),
      N('skiing', 'Лыжи', 'Skiing'),
      N('snowboard', 'Сноуборд', 'Snowboard'),
      N('paddleboard', 'Пэдлборд', 'paddleboard'),
      N('sup', 'Сапборд', 'Paddleboard'),
      N('windsurf', 'Виндсерф', 'windsurf'),
      N('kitesurf', 'Кайт', 'Kitesurf'),
      N('wakeboard', 'Вейкборд', 'wakeboard'),
      N('snorkeling', 'Снорклинг', 'Snorkeling'),
      N('freediving', 'Фридайвинг', 'freediving'),
      N('scuba', 'Дайвинг', 'Scuba'),
    ]),
    N('travel', 'Путешествия', 'Travel', [
      N('roadtrip', 'Роудтрипы', 'Road trips'),
      N('sightseeing', 'По городу', 'Sightseeing'),
      N('vanlife', 'Ванлайф', 'Van life'),
      N('digitalnomad', 'Номадство', 'Digital nomad'),
      N('hostels', 'Хостелы', 'Hostels'),
      N('cityhop', 'Города на выходные', 'City breaks'),
    ]),
    N('fishing', 'Рыбалка', 'Fishing', [
    ]),
    N('naturelife', 'Сад и звёзды', 'Garden & stars', [
      N('birdwatching', 'Птицы', 'Birdwatching'),
      N('foraging', 'Травы и грибы', 'Foraging'),
      N('gardening', 'Сад', 'Gardening'),
      N('plants', 'Растения', 'Plants'),
      N('stargazing', 'Звёзды', 'Stargazing'),
      N('botany', 'Ботаника', 'botany'),
    ]),
    N('adventure', 'Адреналин', 'Adrenaline', [
      N('paragliding', 'Параплан', 'Paragliding'),
      N('skydiving', 'Парашют', 'Skydiving'),
      N('caving', 'Спелео', 'Caving'),
      N('canyoning', 'Каньонинг', 'Canyoning'),
    ]),
  ]),
  TOP('learning', 'Учёба', 'Learning', 'learning', [
    N('language', 'Языки', 'Languages', [
      N('spanish', 'Испанский', 'Spanish'),
      N('english', 'Английский', 'English'),
      N('french', 'Французский', 'French'),
      N('german', 'Немецкий', 'German'),
      N('italian', 'Итальянский', 'Italian'),
      N('portuguese', 'Португальский', 'Portuguese'),
      N('russian', 'Русский', 'russian'),
      N('languages', 'Языки', 'languages'),
      N('exchange', 'Языковой обмен', 'Language exchange'),
      N('practice', 'Практика', 'practice'),
    ]),
    N('skills', 'Курсы и практика', 'Courses & practice', [
      N('course', 'Курсы', 'Courses'),
      N('workshop', 'Воркшопы', 'Workshops'),
      N('study', 'Изучение', 'study'),
      N('bootcamp', 'Буткемпы', 'Bootcamps'),
      N('certification', 'Сертификация', 'certification'),
      N('tutoring', 'Репетиторство', 'Tutoring'),
      N('studygroup', 'Учебная группа', 'Study group'),
    ]),
    N('langs2', 'Другие языки', 'langs2', [
      N('japanese', 'Японский', 'Japanese'),
      N('korean', 'Корейский', 'Korean'),
      N('mandarin', 'Китайский', 'Mandarin'),
      N('chinese', 'Китайский', 'chinese'),
      N('arabic', 'Арабский', 'Arabic'),
      N('catalan', 'Каталанский', 'Catalan'),
      N('dutch', 'Нидерландский', 'dutch'),
      N('swedish', 'Шведский', 'swedish'),
      N('hindi', 'Хинди', 'hindi'),
      N('polish', 'Польский', 'polish'),
      N('turkish', 'Турецкий', 'turkish'),
      N('greek', 'Греческий', 'greek'),
    ]),
    N('academic', 'Наука', 'Science', [
      N('psychology', 'Психология', 'Psychology'),
      N('economics', 'Экономика', 'Economics'),
      N('science', 'Наука вообще', 'Science'),
      N('neuroscience', 'Нейронаука', 'Neuroscience'),
    ]),
    N('personal', 'Навыки', 'Personal skills', [
      N('publicspeaking', 'Публичные выступления', 'Public speaking'),
      N('debate', 'Дебаты', 'Debate'),
      N('productivity', 'Продуктивность', 'Productivity'),
    ]),
  ]),
];
