/**
 * СГЕНЕРИРОВАННЫЙ ФАЙЛ. Не править руками.
 *
 * Источник: kleal-ms/shared/interests.json
 * Обновить: python3 kleal-ms/tools/gen_interests_tree.py --apply
 *
 * Дерево интересов для карты. Раньше оно было отдельным литералом и знало 320 ключей из 447 —
 * остальные не имели подписи и на карту не попадали. Теперь источник общий с сервером: добавить
 * интерес значит дописать строку в реестр, а не в двух местах, которые потом расходятся.
 *
 * Синонимы на экран не идут: football и soccer — один пузырь, второй по-прежнему понимается поиском.
 */
export type TreeNode = { key: string; ru: string; en: string; es: string; icon?: string; kids?: TreeNode[] };

const N = (key: string, ru: string, en: string, es: string, kids?: TreeNode[]): TreeNode =>
  ({ key, ru, en, es, kids });
const TOP = (key: string, ru: string, en: string, es: string, icon: string, kids: TreeNode[]): TreeNode =>
  ({ key, ru, en, es, icon, kids });

export const TREE: TreeNode[] = [
  TOP('sports', 'Спорт', 'Sport', 'Deporte', 'sports', [
    N('team', 'Командный', 'Team', 'De equipo', [
      N('football', 'Футбол', 'Football', 'Fútbol'),
      N('basketball', 'Баскетбол', 'Basketball', 'Baloncesto'),
      N('volleyball', 'Волейбол', 'Volleyball', 'Voleibol'),
      N('handball', 'Гандбол', 'Handball', 'Balonmano'),
      N('rugby', 'Регби', 'Rugby', 'Rugby'),
      N('cricket', 'Крикет', 'cricket', 'Críquet'),
      N('hockey', 'Хоккей', 'Hockey', 'Hockey'),
      N('baseball', 'Бейсбол', 'baseball', 'Béisbol'),
      N('futsal', 'Мини-футбол', 'Futsal', 'Fútbol sala'),
      N('ultimate', 'Фрисби', 'ultimate', 'Ultimate'),
      N('waterpolo', 'Водное поло', 'waterpolo', 'Waterpolo'),
    ]),
    N('racket', 'Ракетки', 'Racquets', 'De raqueta', [
      N('tennis', 'Теннис', 'Tennis', 'Tenis'),
      N('padel', 'Падел', 'Padel', 'Pádel'),
      N('badminton', 'Бадминтон', 'Badminton', 'Bádminton'),
      N('squash', 'Сквош', 'Squash', 'Squash'),
      N('pingpong', 'Настольный теннис', 'Ping-pong', 'Ping-pong'),
      N('tabletennis', 'Настольный теннис', 'tabletennis', 'Tenis de mesa'),
      N('pickleball', 'Пиклбол', 'Pickleball', 'Pickleball'),
      N('racquetball', 'Ракетбол', 'racquetball', 'Racquetball'),
    ]),
    N('endurance', 'Выносливость', 'Endurance', 'Resistencia', [
      N('running', 'Бег', 'Running', 'Correr'),
      N('cycling', 'Вело', 'Cycling', 'Ciclismo'),
      N('swimming', 'Плавание', 'Swimming', 'Natación'),
      N('triathlon', 'Триатлон', 'Triathlon', 'Triatlón'),
      N('marathon', 'Марафон', 'Marathon', 'Maratón'),
      N('rowing', 'Гребля', 'Rowing', 'Remo'),
      N('spinning', 'Велотренажер', 'spinning', 'Spinning'),
      N('hyrox', 'Hyrox', 'hyrox', 'Hyrox'),
      N('duathlon', 'Дуатлон', 'duathlon', 'Duatlon'),
    ]),
    N('strength', 'Зал и сила', 'Gym & strength', 'Gimnasio y fuerza', [
      N('gym', 'Зал', 'Gym', 'Gimnasio'),
      N('fitness', 'Фитнес', 'fitness', 'Fitness'),
      N('crossfit', 'Кроссфит', 'CrossFit', 'CrossFit'),
      N('boxing', 'Бокс', 'Boxing', 'Boxeo'),
      N('mma', 'ММА', 'MMA', 'MMA'),
      N('climbing', 'Скалолазание', 'Climbing', 'Escalada'),
      N('bouldering', 'Боулдеринг', 'Bouldering', 'Boulder'),
      N('calisthenics', 'Турники', 'Calisthenics', 'Calistenia'),
      N('powerlifting', 'Пауэрлифтинг', 'Powerlifting', 'Powerlifting'),
      N('weightlifting', 'Тяжелая атлетика', 'weightlifting', 'Halterofilia'),
      N('kettlebell', 'Гири', 'kettlebell', 'Kettlebell'),
      N('kickboxing', 'Кикбоксинг', 'kickboxing', 'Kickboxing'),
      N('judo', 'Дзюдо', 'judo', 'Jujitsu'),
      N('karate', 'Карате', 'karate', 'Kárate'),
      N('bjj', 'Джиу-джитсу', 'BJJ', 'BJJ'),
      N('wrestling', 'Борьба', 'wrestling', 'Lucha libre'),
      N('muaythai', 'Муай тай', 'muaythai', 'Muay thai'),
      N('fencing', 'Фехтование', 'fencing', 'Esgrima'),
    ]),
    N('mindbody', 'Тело и практики', 'Body & practice', 'Cuerpo y práctica', [
      N('yoga', 'Йога', 'Yoga', 'Yoga'),
      N('pilates', 'Пилатес', 'Pilates', 'Pilates'),
      N('stretching', 'Растяжка', 'Stretching', 'Estiramientos'),
      N('meditation', 'Медитация', 'Meditation', 'Meditación'),
      N('breathwork', 'Дыхание', 'Breathwork', 'Técnicas de respiración'),
      N('taichi', 'Тайцзи', 'Tai chi', 'Tai Chi'),
      N('qigong', 'Цигун', 'qigong', 'Qigong'),
    ]),
  ]),
  TOP('social', 'Общение', 'Social', 'Social', 'social', [
    N('coffee', 'Кофе', 'Coffee', 'Café', [
      N('tea', 'Чай', 'Tea', 'Té'),
      N('brunch', 'Бранчи', 'Brunch', 'Brunch'),
      N('cafe', 'По кофейням', 'Cafe hopping', 'Cafeterías'),
      N('matcha', 'Матча', 'Matcha', 'Matcha'),
      N('espresso', 'Эспрессо', 'Espresso', 'Café expreso'),
    ]),
    N('dining', 'Поесть', 'Eating out', 'Comer fuera', [
      N('dinner', 'Ужины', 'Dinners', 'Cenas'),
      N('lunch', 'Обед', 'lunch', 'Almuerzo'),
      N('food', 'Еда', 'food', 'Comida'),
      N('restaurant', 'Рестораны', 'Restaurants', 'Restaurantes'),
      N('cooking', 'Готовка', 'Cooking', 'Cocina'),
    ]),
    N('nightlife', 'Ночная жизнь', 'Nightlife', 'Vida nocturna', [
      N('bar', 'Бары', 'Bars', 'Bares'),
      N('drinks', 'Напитки', 'drinks', 'Bebidas'),
      N('pub', 'Паб', 'pub', 'Pub'),
      N('beer', 'Пиво', 'Beer', 'Cerveza'),
      N('wine', 'Вино', 'Wine', 'Vino'),
      N('party', 'Вечеринки', 'Parties', 'Fiestas'),
      N('club', 'Клубы', 'Clubs', 'Discotecas'),
      N('clubbing', 'Клуб', 'clubbing', 'Clubbing'),
      N('cocktails', 'Коктейли', 'Cocktails', 'Cócteles'),
      N('mezcal', 'Мескаль', 'mezcal', 'Mezcal'),
      N('sake', 'Саке', 'sake', 'Sake'),
    ]),
    N('casual', 'Просто погулять', 'Just hang out', 'Pasear', [
      N('walk', 'Прогулки', 'Walks', 'Paseos'),
      N('walking', 'Ходьба', 'walking', 'Caminata'),
      N('stroll', 'Прогулка', 'stroll', 'Paseo'),
      N('hang', 'Встреча', 'hang', 'Reunión'),
      N('hangout', 'Поболтать', 'Hang out', 'Charlar'),
      N('chill', 'Релакс', 'chill', 'Relax'),
      N('talk', 'Разговор', 'talk', 'Charla'),
      N('chat', 'Болтовня', 'chat', 'Charla'),
      N('park', 'Парки', 'Parks', 'Parques'),
      N('terrace', 'Террасы', 'Terraces', 'Terrazas'),
    ]),
    N('foodie', 'Гурман', 'foodie', 'Gourmet', [
      N('baking', 'Выпечка', 'Baking', 'Panadería'),
      N('bbq', 'Барбекю', 'bbq', 'Barbacoa'),
      N('streetfood', 'Стритфуд', 'Street food', 'Comida callejera'),
      N('vegan', 'Веган', 'Vegan', 'Vegano'),
      N('vegetarian', 'Вегетарианство', 'vegetarian', 'Vegetarianismo'),
      N('tapas', 'Тапас', 'Tapas', 'Tapas'),
      N('sushi', 'Суши', 'Sushi', 'Sushi'),
      N('picnic', 'Пикники', 'Picnics', 'Pícnic'),
      N('ramen', 'Рамен', 'Ramen', 'Ramen'),
      N('pizza', 'Пицца', 'pizza', 'Pizza'),
      N('pasta', 'Паста', 'pasta', 'Pasta'),
    ]),
    N('wellness', 'Спа и забота', 'Spa & self-care', 'Spa y autocuidado', [
      N('spa', 'Спа', 'Spa', 'Spa'),
      N('sauna', 'Сауна', 'Sauna', 'Sauna'),
      N('selfcare', 'Забота о себе', 'Self-care', 'Autocuidado'),
      N('massage', 'Массаж', 'Massage', 'Masaje'),
    ]),
    N('community', 'Волонтёрство', 'Volunteering', 'Voluntariado', [
      N('volunteering', 'Помогать', 'Volunteering', 'Ayudar'),
      N('charity', 'Благотворительность', 'Charity', 'Beneficencia'),
      N('meetup', 'Митапы', 'Meetups', 'Encuentros'),
      N('activism', 'Активизм', 'Activism', 'Activismo'),
      N('sustainability', 'Экология', 'Sustainability', 'Sostenibilidad'),
    ]),
    N('pets', 'Питомцы', 'Pets', 'Mascotas', [
      N('dogs', 'Собаки', 'Dogs', 'Perros'),
      N('dog', 'Собака', 'dog', 'Perro'),
      N('cats', 'Кошки', 'Cats', 'Gatos'),
      N('dogwalk', 'Выгул вместе', 'Dog walks', 'Paseos con perros'),
    ]),
    N('family', 'Семья и дети', 'Family & kids', 'Familia y niños', [
      N('parenting', 'Родительство', 'Parenting', 'Parentalidad'),
      N('kids', 'С детьми', 'With kids', 'Con niños'),
      N('playdate', 'Плейдейты', 'Playdates', 'Juegos en grupo'),
      N('mums', 'Мамы', 'mums', 'Mamás'),
    ]),
  ]),
  TOP('games', 'Игры', 'Games', 'Juegos', 'games', [
    N('esports', 'Киберспорт', 'Esports', 'E-sports', [
      N('dota', 'Dota', 'Dota', 'Dota'),
      N('valorant', 'Valorant', 'Valorant', 'Valorant'),
      N('cs', 'CS', 'CS', 'CS'),
      N('league', 'League of Legends', 'League of Legends', 'League of Legends'),
      N('apex', 'Apex', 'Apex', 'Apex'),
      N('fortnite', 'Фортнайт', 'fortnite', 'Fortnite'),
      N('fifa', 'FIFA', 'FIFA', 'FIFA'),
      N('overwatch', 'Overwatch', 'Overwatch', 'Overwatch'),
      N('gaming', 'Игры', 'gaming', 'Juegos'),
      N('rocketleague', 'Rocket League', 'Rocket League', 'Rocket League'),
      N('r6', 'Rainbow Six', 'r6', 'Rainbow six'),
      N('rainbow6', 'Рейнбоу', 'rainbow6', 'Rainbow six'),
      N('starcraft', 'Старкрафт', 'starcraft', 'Starcraft'),
      N('hearthstone', 'Коллекционная карта', 'hearthstone', 'Hearthstone'),
      N('tekken', 'Tekken', 'tekken', 'Tekken'),
      N('smash', 'Smash Bros', 'smash', 'Smash'),
      N('cod', 'Шутер', 'cod', 'Call of duty'),
      N('warzone', 'Батл-рояль', 'warzone', 'Warzone'),
    ]),
    N('tabletop', 'Настолки', 'Board games', 'Juegos de mesa', [
      N('chess', 'Шахматы', 'Chess', 'Ajedrez'),
      N('boardgames', 'Настольные', 'Board games', 'Juegos de mesa'),
      N('poker', 'Покер', 'Poker', 'Póker'),
      N('cards', 'Карты', 'cards', 'Baraja'),
      N('dnd', 'Ролевые', 'Tabletop RPG', 'RPG de mesa'),
      N('catan', 'Катан', 'Catan', 'Catan'),
      N('monopoly', 'Монополия', 'monopoly', 'Monopolio'),
      N('risk', 'Риск', 'risk', 'Risk'),
      N('magic', 'Magic', 'Magic', 'Magic'),
      N('mtg', 'Мэджик', 'mtg', 'Magic'),
      N('warhammer', 'Warhammer', 'Warhammer', 'Warhammer'),
      N('ttrpg', 'Ролевая игра', 'ttrpg', 'Rol'),
      N('trivia', 'Квизы', 'Trivia', 'Cuestionario'),
      N('quiz', 'Викторина', 'quiz', 'Cuestionario'),
      N('mahjong', 'Маджонг', 'mahjong', 'Mahjong'),
      N('backgammon', 'Нарды', 'Backgammon', 'Backgammon'),
      N('escaperoom', 'Квесты', 'Escape rooms', 'Escape room'),
    ]),
    N('console', 'Консоли', 'Console', 'Consola', [
      N('playstation', 'PlayStation', 'PlayStation', 'PlayStation'),
      N('xbox', 'Xbox', 'Xbox', 'Xbox'),
      N('nintendo', 'Nintendo', 'Nintendo', 'Nintendo'),
      N('switch', 'Нинтендо', 'switch', 'Switch'),
    ]),
    N('pc', 'PC', 'PC', 'PC', [
      N('minecraft', 'Minecraft', 'Minecraft', 'Minecraft'),
      N('roblox', 'Роблокс', 'roblox', 'Roblox'),
      N('valheim', 'Valheim', 'Valheim', 'Valheim'),
      N('terraria', 'Terraria', 'Terraria', 'Terraria'),
      N('stardew', 'Stardew Valley', 'Stardew Valley', 'Stardew Valley'),
    ]),
    N('mobile', 'Мобильные игры', 'mobile', 'Móvil', [
      N('clashroyale', 'Clash Royale', 'Clash Royale', 'Clash Royale'),
      N('pubg', 'PUBG', 'PUBG', 'PUBG'),
      N('genshin', 'Genshin', 'Genshin', 'Genshin'),
      N('mobilegaming', 'Мобильные', 'Mobile', 'Móvil'),
    ]),
  ]),
  TOP('culture', 'Культура', 'Culture', 'Cultura', 'culture', [
    N('screen', 'Кино и сериалы', 'Films & series', 'Películas y series', [
      N('cinema', 'Кино', 'Films', 'Películas'),
      N('series', 'Сериалы', 'Series', 'Series'),
      N('documentary', 'Документальное', 'Documentary', 'Documentales'),
      N('netflix', 'Нетфликс', 'netflix', 'Netflix'),
      N('marvel', 'Marvel', 'Marvel', 'Marvel'),
      N('sitcom', 'Ситкомы', 'Sitcoms', 'Sitcoms'),
    ]),
    N('visual', 'Искусство', 'Art', 'Arte', [
      N('art', 'Искусство', 'art', 'Arte'),
      N('museum', 'Музеи', 'Museums', 'Museos'),
      N('gallery', 'Галереи', 'Galleries', 'Galerías'),
      N('photography', 'Фотография', 'Photography', 'Fotografía'),
      N('exhibition', 'Выставки', 'Exhibitions', 'Exposiciones'),
      N('painting', 'Живопись', 'Painting', 'Pintura'),
      N('sketching', 'Скетчинг', 'Sketching', 'Dibujo'),
      N('illustration', 'Иллюстрация', 'illustration', 'Ilustración'),
      N('streetart', 'Стритарт', 'Street art', 'Arte urbano'),
      N('graffiti', 'Граффити', 'graffiti', 'Grafiti'),
      N('sculpture', 'Скульптура', 'sculpture', 'Escultura'),
    ]),
    N('stage', 'Сцена', 'Stage', 'Escena', [
      N('theatre', 'Театр', 'Theatre', 'Teatro'),
      N('opera', 'Опера', 'Opera', 'Ópera'),
      N('ballet', 'Балет', 'Ballet', 'Ballet'),
      N('standup', 'Стендап', 'Stand-up', 'Stand-up'),
      N('comedy', 'Комедия', 'comedy', 'Comedia'),
      N('improv', 'Импров', 'Improv', 'Improvisación'),
      N('musical', 'Мюзиклы', 'Musicals', 'Musicales'),
      N('circus', 'Цирк', 'circus', 'Circo'),
    ]),
    N('reading', 'Книги', 'Books', 'Libros', [
      N('books', 'Читать', 'Reading', 'Lectura'),
      N('literature', 'Классика', 'Literature', 'Literatura'),
      N('bookclub', 'Книжный клуб', 'Book club', 'Club de lectura'),
      N('scifi', 'Фантастика', 'Sci-fi', 'Ciencia ficción'),
      N('fantasy', 'Фэнтези', 'Fantasy', 'Fantasía'),
      N('nonfiction', 'Нон-фикшн', 'Non-fiction', 'No ficción'),
    ]),
    N('urbanism', 'Урбанистика', 'Urbanism', 'Urbanismo', [
      N('architecture', 'Архитектура', 'Architecture', 'Arquitectura'),
      N('city', 'Город', 'city', 'Ciudad'),
    ]),
    N('anime', 'Аниме и Азия', 'Anime & Asia', 'Anime y Asia', [
      N('manga', 'Манга', 'Manga', 'Manga'),
      N('kdrama', 'К-дорамы', 'K-drama', 'K-drama'),
      N('cosplay', 'Косплей', 'Cosplay', 'Cosplay'),
      N('kpop', 'K-pop', 'K-pop', 'K-pop'),
      N('cartoons', 'Мультфильмы', 'Cartoons', 'Dibujos animados'),
    ]),
    N('craft', 'Рукоделие', 'Craft', 'Artesanía', [
      N('pottery', 'Керамика', 'Pottery', 'Cerámica'),
      N('ceramics', 'Керамика', 'ceramics', 'Cerámica'),
      N('knitting', 'Вязание', 'Knitting', 'Tejido'),
      N('crochet', 'Вязание крючком', 'crochet', 'Ganchillo'),
      N('sewing', 'Шитьё', 'Sewing', 'Costura'),
      N('woodworking', 'Дерево', 'Woodworking', 'Trabajo en madera'),
      N('calligraphy', 'Каллиграфия', 'Calligraphy', 'Caligrafía'),
      N('diy', 'Своими руками', 'DIY', 'Manualidades'),
    ]),
    N('writing', 'Тексты', 'Writing', 'Escritura', [
      N('poetry', 'Поэзия', 'Poetry', 'Poesía'),
      N('journaling', 'Дневник', 'Journaling', 'Diario'),
      N('blogging', 'Блог', 'Blogging', 'Blog'),
    ]),
    N('history', 'История и город', 'History & city', 'Historia y ciudad', [
      N('heritage', 'Наследие', 'Heritage', 'Patrimonio'),
      N('archaeology', 'Археология', 'Archaeology', 'Arqueología'),
    ]),
  ]),
  TOP('tech', 'Дело', 'Work & tech', 'Trabajo y tecnología', 'tech', [
    N('startups', 'Стартапы', 'Startups', 'Startups', [
      N('startup', 'Свой проект', 'Own project', 'Mi proyecto'),
      N('product', 'Продукт', 'Product', 'Producto'),
      N('founder', 'Основателям', 'Founders', 'Fundadores'),
      N('entrepreneur', 'Предпринимательство', 'Entrepreneurship', 'Emprendimiento'),
      N('business', 'Бизнес', 'Business', 'Negocio'),
    ]),
    N('engineering', 'Код и ИИ', 'Code & AI', 'Código e IA', [
      N('ai', 'ИИ', 'AI', 'IA'),
      N('programming', 'Программирование', 'programming', 'Programación'),
      N('coding', 'Программирование', 'Coding', 'Programación'),
      N('software', 'Программное обеспечение', 'software', 'Software'),
      N('data', 'Данные', 'Data', 'Datos'),
      N('crypto', 'Криптовалюты', 'Crypto', 'Criptomonedas'),
      N('blockchain', 'Блокчейн', 'blockchain', 'Blockchain'),
      N('devops', 'DevOps', 'DevOps', 'DevOps'),
      N('cloud', 'Облако', 'cloud', 'Nube'),
      N('cybersecurity', 'Безопасность', 'Security', 'Seguridad'),
      N('security', 'Безопасность', 'security', 'Seguridad'),
      N('python', 'Python', 'Python', 'Python'),
      N('javascript', 'JavaScript', 'JavaScript', 'JavaScript'),
      N('rust', 'Rust', 'Rust', 'Rust'),
      N('golang', 'Go', 'golang', 'Go'),
      N('opensource', 'Опенсорс', 'Open source', 'Código abierto'),
      N('frontend', 'Фронтенд', 'frontend', 'Frontend'),
      N('backend', 'Бэкенд', 'backend', 'Backend'),
    ]),
    N('career', 'Карьера и связи', 'Career & network', 'Carrera y red', [
      N('networking', 'Нетворкинг', 'Networking', 'Networking'),
      N('investing', 'Инвестиции', 'Investing', 'Inversión'),
      N('investor', 'Инвестор', 'investor', 'Inversor'),
      N('mentorship', 'Менторство', 'Mentorship', 'Mentoría'),
      N('consulting', 'Консалтинг', 'consulting', 'Consultoría'),
      N('finance', 'Финансы', 'Finance', 'Finanzas'),
      N('vc', 'Венчурный капитал', 'vc', 'Capital de riesgo'),
      N('freelance', 'Фриланс', 'Freelance', 'Freelance'),
      N('remote', 'Удалёнка', 'Remote', 'Remoto'),
      N('coworking', 'Коворкинг', 'Coworking', 'Coworking'),
    ]),
    N('design', 'Дизайн', 'Design', 'Diseño', [
      N('ux', 'UX', 'UX', 'UX'),
      N('ui', 'UI', 'UI', 'UI'),
      N('figma', 'Figma', 'Figma', 'Figma'),
      N('branding', 'Бренд', 'Branding', 'Branding'),
      N('typography', 'Типографика', 'Typography', 'Tipografía'),
      N('motion', 'Моушн', 'Motion', 'Motion'),
    ]),
    N('dataai', 'Данные и ИИ', 'dataai', 'Datos e IA', [
      N('datascience', 'Data Science', 'datascience', 'Ciencia de datos'),
      N('analytics', 'Аналитика', 'analytics', 'Análisis'),
      N('statistics', 'Статистика', 'statistics', 'Estadística'),
      N('bigdata', 'Большие данные', 'bigdata', 'Big data'),
    ]),
    N('web3', 'Крипта', 'Crypto', 'Cripto', [
      N('defi', 'DeFi', 'DeFi', 'DeFi'),
      N('nft', 'NFT', 'NFT', 'NFT'),
      N('dao', 'DAO', 'DAO', 'DAO'),
      N('ethereum', 'Эфир', 'Ethereum', 'Ethereum'),
      N('bitcoin', 'Биткоин', 'Bitcoin', 'Bitcoin'),
      N('solidity', 'Solidity', 'solidity', 'Solidity'),
      N('degen', 'Degen', 'degen', 'Degen'),
    ]),
    N('growth', 'Маркетинг', 'Marketing', 'Marketing', [
      N('marketing', 'Маркетинг', 'Marketing', 'Marketing'),
      N('sales', 'Продажи', 'Sales', 'Ventas'),
      N('saas', 'SaaS', 'SaaS', 'SaaS'),
      N('b2b', 'B2B', 'b2b', 'B2B'),
      N('pm', 'Продакт-менеджмент', 'Product management', 'Gestión de producto'),
    ]),
  ]),
  TOP('music', 'Музыка', 'Music', 'Música', 'music', [
    N('listening', 'Концерты', 'Live music', 'Música en vivo', [
      N('concert', 'Концерты', 'Concerts', 'Conciertos'),
      N('gig', 'Небольшие площадки', 'Small gigs', 'Pequeños conciertos'),
      N('festival', 'Фестивали', 'Festivals', 'Festivales'),
      N('music', 'Музыка', 'Music', 'Música'),
      N('vinyl', 'Винил', 'Vinyl', 'Vinilo'),
      N('livemusic', 'Живая музыка', 'Live music', 'Música en vivo'),
      N('playlist', 'Плейлист', 'playlist', 'Playlist'),
    ]),
    N('making', 'Играю сам', 'I play', 'Yo toco', [
      N('guitar', 'Гитара', 'Guitar', 'Guitarra'),
      N('piano', 'Пианино', 'Piano', 'Piano'),
      N('drums', 'Барабаны', 'Drums', 'Batería'),
      N('dj', 'Диджеинг', 'DJing', 'Dj'),
      N('jam', 'Джем', 'jam', 'Jam'),
      N('producing', 'Продакшн', 'Producing', 'Producción'),
      N('singing', 'Вокал', 'Singing', 'Canto'),
      N('karaoke', 'Караоке', 'Karaoke', 'Karaoke'),
      N('band', 'Группа', 'Band', 'Banda'),
      N('bass', 'Бас', 'Bass', 'Bajo'),
      N('synth', 'Синтезатор', 'synth', 'Sintetizador'),
      N('ableton', 'Ableton', 'ableton', 'Ableton'),
      N('songwriting', 'Песни', 'songwriting', 'Escritura de canciones'),
      N('choir', 'Хор', 'choir', 'Coro'),
    ]),
    N('electronic', 'Электроника', 'Electronic', 'Electrónica', [
      N('rave', 'Рейвы', 'Raves', 'Raves'),
      N('techno', 'Техно', 'Techno', 'Techno'),
      N('edm', 'EDM', 'EDM', 'EDM'),
    ]),
    N('genres', 'Жанры', 'Genres', 'Géneros', [
      N('jazz', 'Джаз', 'Jazz', 'Jazz'),
      N('rock', 'Рок', 'Rock', 'Rock'),
      N('hiphop', 'Хип-хоп', 'Hip-hop', 'Hip-hop'),
      N('rap', 'Рэп', 'rap', 'Rap'),
      N('classical', 'Классика', 'Classical', 'Clásica'),
      N('indie', 'Инди', 'Indie', 'Indie'),
      N('pop', 'Поп', 'pop', 'Pop'),
      N('metal', 'Метал', 'Metal', 'Metal'),
      N('punk', 'Панк', 'punk', 'Punk'),
      N('reggae', 'Регги', 'reggae', 'Reggae'),
      N('funk', 'Фанк', 'Funk', 'Funk'),
      N('soul', 'Соул', 'Soul', 'Soul'),
      N('house', 'Хаус', 'House', 'House'),
      N('disco', 'Диско', 'disco', 'Disco'),
    ]),
    N('dance', 'Танцы', 'Dance', 'Danza', [
      N('salsa', 'Сальса', 'Salsa', 'Salsa'),
      N('bachata', 'Бачата', 'Bachata', 'Bachata'),
      N('tango', 'Танго', 'Tango', 'Tango'),
      N('swing', 'Свинг', 'Swing', 'Swing'),
      N('ballroom', 'Бальные', 'Ballroom', 'Bailables'),
      N('zumba', 'Зумба', 'Zumba', 'Zumba'),
    ]),
  ]),
  TOP('outdoors', 'Природа', 'Outdoors', 'Naturaleza', 'outdoors', [
    N('hiking', 'Походы', 'Hiking', 'Senderismo', [
      N('trekking', 'Треккинг', 'Trekking', 'Trekking'),
      N('nature', 'Природа', 'nature', 'Naturaleza'),
      N('camping', 'Кемпинг', 'Camping', 'Camping'),
      N('mountains', 'Горы', 'Mountains', 'Montañas'),
      N('trail', 'Тропы', 'Trails', 'Senderos'),
      N('outdoor', 'На открытом воздухе', 'outdoor', 'Al aire libre'),
      N('outdoors', 'Природа', 'Outdoors', 'Naturaleza'),
      N('backpacking', 'С рюкзаком', 'Backpacking', 'Rutas con mochila'),
      N('trailrunning', 'Трейлраннинг', 'Trail running', 'Trail running'),
      N('mountaineering', 'Альпинизм', 'mountaineering', 'Alpinismo'),
    ]),
    N('watersnow', 'Вода и снег', 'Water & snow', 'Agua y nieve', [
      N('surfing', 'Сёрфинг', 'Surfing', 'Surf'),
      N('kayaking', 'Каяк', 'Kayaking', 'Kayak'),
      N('skiing', 'Лыжи', 'Skiing', 'Esquí'),
      N('snowboard', 'Сноуборд', 'Snowboard', 'Snowboard'),
      N('paddleboard', 'Пэдлборд', 'paddleboard', 'Paddleboard'),
      N('sup', 'Сапборд', 'Paddleboard', 'Paddleboard'),
      N('windsurf', 'Виндсерф', 'windsurf', 'Windsurf'),
      N('kitesurf', 'Кайт', 'Kitesurf', 'Kitesurf'),
      N('wakeboard', 'Вейкборд', 'wakeboard', 'Wakeboard'),
      N('snorkeling', 'Снорклинг', 'Snorkeling', 'Snorkel'),
      N('freediving', 'Фридайвинг', 'freediving', 'Freediving'),
      N('scuba', 'Дайвинг', 'Scuba', 'Buceo'),
    ]),
    N('travel', 'Путешествия', 'Travel', 'Viajar', [
      N('roadtrip', 'Роудтрипы', 'Road trips', 'Road trips'),
      N('sightseeing', 'По городу', 'Sightseeing', 'Turismo'),
      N('vanlife', 'Ванлайф', 'Van life', 'Van life'),
      N('digitalnomad', 'Номадство', 'Digital nomad', 'Digital nomad'),
      N('hostels', 'Хостелы', 'Hostels', 'Albergues'),
      N('cityhop', 'Города на выходные', 'City breaks', 'Escapadas urbanas'),
    ]),
    N('fishing', 'Рыбалка', 'Fishing', 'Pesca', [
    ]),
    N('naturelife', 'Сад и звёзды', 'Garden & stars', 'Jardín y estrellas', [
      N('birdwatching', 'Птицы', 'Birdwatching', 'Observación de aves'),
      N('foraging', 'Травы и грибы', 'Foraging', 'Recolección'),
      N('gardening', 'Сад', 'Gardening', 'Jardinería'),
      N('plants', 'Растения', 'Plants', 'Plantas'),
      N('stargazing', 'Звёзды', 'Stargazing', 'Astronomía'),
      N('botany', 'Ботаника', 'botany', 'Botánica'),
    ]),
    N('adventure', 'Адреналин', 'Adrenaline', 'Aventura', [
      N('paragliding', 'Параплан', 'Paragliding', 'Parapente'),
      N('skydiving', 'Парашют', 'Skydiving', 'Paracaidismo'),
      N('caving', 'Спелео', 'Caving', 'Espeleología'),
      N('canyoning', 'Каньонинг', 'Canyoning', 'Barranquismo'),
    ]),
  ]),
  TOP('learning', 'Учёба', 'Learning', 'Aprendizaje', 'learning', [
    N('language', 'Языки', 'Languages', 'Idiomas', [
      N('spanish', 'Испанский', 'Spanish', 'Español'),
      N('english', 'Английский', 'English', 'Inglés'),
      N('french', 'Французский', 'French', 'Francés'),
      N('german', 'Немецкий', 'German', 'Alemán'),
      N('italian', 'Итальянский', 'Italian', 'Italiano'),
      N('portuguese', 'Португальский', 'Portuguese', 'Portugués'),
      N('russian', 'Русский', 'russian', 'Ruso'),
      N('languages', 'Языки', 'languages', 'Lenguas'),
      N('exchange', 'Языковой обмен', 'Language exchange', 'Intercambio de idiomas'),
      N('practice', 'Практика', 'practice', 'Práctica'),
    ]),
    N('skills', 'Курсы и практика', 'Courses & practice', 'Cursos y práctica', [
      N('course', 'Курсы', 'Courses', 'Cursos'),
      N('workshop', 'Воркшопы', 'Workshops', 'Talleres'),
      N('study', 'Изучение', 'study', 'Estudio'),
      N('bootcamp', 'Буткемпы', 'Bootcamps', 'Bootcamps'),
      N('certification', 'Сертификация', 'certification', 'Certificación'),
      N('tutoring', 'Репетиторство', 'Tutoring', 'Tutoría'),
      N('studygroup', 'Учебная группа', 'Study group', 'Grupo de estudio'),
    ]),
    N('langs2', 'Другие языки', 'langs2', 'Otras lenguas', [
      N('japanese', 'Японский', 'Japanese', 'Japonés'),
      N('korean', 'Корейский', 'Korean', 'Coreano'),
      N('mandarin', 'Китайский', 'Mandarin', 'Mandarín'),
      N('chinese', 'Китайский', 'chinese', 'Chino'),
      N('arabic', 'Арабский', 'Arabic', 'Árabe'),
      N('catalan', 'Каталанский', 'Catalan', 'Catalán'),
      N('dutch', 'Нидерландский', 'dutch', 'Neerlandés'),
      N('swedish', 'Шведский', 'swedish', 'Sueco'),
      N('hindi', 'Хинди', 'hindi', 'Hindi'),
      N('polish', 'Польский', 'polish', 'Polaco'),
      N('turkish', 'Турецкий', 'turkish', 'Turco'),
      N('greek', 'Греческий', 'greek', 'Griego'),
    ]),
    N('academic', 'Наука', 'Science', 'Ciencia', [
      N('psychology', 'Психология', 'Psychology', 'Psicología'),
      N('economics', 'Экономика', 'Economics', 'Economía'),
      N('science', 'Наука вообще', 'Science', 'Ciencia'),
      N('neuroscience', 'Нейронаука', 'Neuroscience', 'Neurociencia'),
    ]),
    N('personal', 'Навыки', 'Personal skills', 'Habilidades personales', [
      N('publicspeaking', 'Публичные выступления', 'Public speaking', 'Oratoria'),
      N('debate', 'Дебаты', 'Debate', 'Debate'),
      N('productivity', 'Продуктивность', 'Productivity', 'Productividad'),
    ]),
  ]),
];
